INSERT INTO public.geo_cities_municipalities (code, province_code, name)
VALUES
  ('PH-ABR-BANGUED', 'PH-ABR', 'Bangued'),
  ('PH-ABR-BOLINEY', 'PH-ABR', 'Boliney'),
  ('PH-ABR-BUCAY', 'PH-ABR', 'Bucay'),
  ('PH-ABR-BUCLOC', 'PH-ABR', 'Bucloc'),
  ('PH-ABR-DAGUIOMAN', 'PH-ABR', 'Daguioman'),
  ('PH-ABR-DANGLAS', 'PH-ABR', 'Danglas'),
  ('PH-ABR-DOLORES', 'PH-ABR', 'Dolores'),
  ('PH-ABR-LA-PAZ', 'PH-ABR', 'La Paz'),
  ('PH-ABR-LACUB', 'PH-ABR', 'Lacub'),
  ('PH-ABR-LAGANGILANG', 'PH-ABR', 'Lagangilang'),
  ('PH-ABR-LAGAYAN', 'PH-ABR', 'Lagayan'),
  ('PH-ABR-LANGIDEN', 'PH-ABR', 'Langiden'),
  ('PH-ABR-LICUAN-BAAY-LICUAN', 'PH-ABR', 'Licuan-Baay (Licuan)'),
  ('PH-ABR-LUBA', 'PH-ABR', 'Luba'),
  ('PH-ABR-MALIBCONG', 'PH-ABR', 'Malibcong'),
  ('PH-ABR-MANABO', 'PH-ABR', 'Manabo'),
  ('PH-ABR-PENARRUBIA', 'PH-ABR', 'Peñarrubia'),
  ('PH-ABR-PIDIGAN', 'PH-ABR', 'Pidigan'),
  ('PH-ABR-PILAR', 'PH-ABR', 'Pilar'),
  ('PH-ABR-SALLAPADAN', 'PH-ABR', 'Sallapadan'),
  ('PH-ABR-SAN-ISIDRO', 'PH-ABR', 'San Isidro'),
  ('PH-ABR-SAN-JUAN', 'PH-ABR', 'San Juan'),
  ('PH-ABR-SAN-QUINTIN', 'PH-ABR', 'San Quintin'),
  ('PH-ABR-TAYUM', 'PH-ABR', 'Tayum'),
  ('PH-ABR-TINEG', 'PH-ABR', 'Tineg'),
  ('PH-ABR-TUBO', 'PH-ABR', 'Tubo'),
  ('PH-ABR-VILLAVICIOSA', 'PH-ABR', 'Villaviciosa'),
  ('PH-AGN-BUENAVISTA', 'PH-AGN', 'Buenavista'),
  ('PH-AGN-BUTUAN-CITY', 'PH-AGN', 'Butuan City'),
  ('PH-AGN-CABADBARAN-CITY', 'PH-AGN', 'Cabadbaran City'),
  ('PH-AGN-CARMEN', 'PH-AGN', 'Carmen'),
  ('PH-AGN-JABONGA', 'PH-AGN', 'Jabonga'),
  ('PH-AGN-KITCHARAO', 'PH-AGN', 'Kitcharao'),
  ('PH-AGN-LAS-NIEVES', 'PH-AGN', 'Las Nieves'),
  ('PH-AGN-MAGALLANES', 'PH-AGN', 'Magallanes'),
  ('PH-AGN-NASIPIT', 'PH-AGN', 'Nasipit'),
  ('PH-AGN-REMEDIOS-T-ROMUALDEZ', 'PH-AGN', 'Remedios T. Romualdez'),
  ('PH-AGN-SANTIAGO', 'PH-AGN', 'Santiago'),
  ('PH-AGN-TUBAY', 'PH-AGN', 'Tubay'),
  ('PH-AGS-BAYUGAN-CITY', 'PH-AGS', 'Bayugan City'),
  ('PH-AGS-BUNAWAN', 'PH-AGS', 'Bunawan'),
  ('PH-AGS-ESPERANZA', 'PH-AGS', 'Esperanza'),
  ('PH-AGS-LA-PAZ', 'PH-AGS', 'La Paz'),
  ('PH-AGS-LORETO', 'PH-AGS', 'Loreto'),
  ('PH-AGS-PROSPERIDAD', 'PH-AGS', 'Prosperidad'),
  ('PH-AGS-ROSARIO', 'PH-AGS', 'Rosario'),
  ('PH-AGS-SAN-FRANCISCO', 'PH-AGS', 'San Francisco'),
  ('PH-AGS-SAN-LUIS', 'PH-AGS', 'San Luis'),
  ('PH-AGS-SANTA-JOSEFA', 'PH-AGS', 'Santa Josefa'),
  ('PH-AGS-SIBAGAT', 'PH-AGS', 'Sibagat'),
  ('PH-AGS-TALACOGON', 'PH-AGS', 'Talacogon'),
  ('PH-AGS-TRENTO', 'PH-AGS', 'Trento'),
  ('PH-AGS-VERUELA', 'PH-AGS', 'Veruela'),
  ('PH-AKL-ALTAVAS', 'PH-AKL', 'Altavas'),
  ('PH-AKL-BALETE', 'PH-AKL', 'Balete'),
  ('PH-AKL-BANGA', 'PH-AKL', 'Banga'),
  ('PH-AKL-BATAN', 'PH-AKL', 'Batan'),
  ('PH-AKL-BURUANGA', 'PH-AKL', 'Buruanga'),
  ('PH-AKL-IBAJAY', 'PH-AKL', 'Ibajay'),
  ('PH-AKL-KALIBO', 'PH-AKL', 'Kalibo'),
  ('PH-AKL-LEZO', 'PH-AKL', 'Lezo'),
  ('PH-AKL-LIBACAO', 'PH-AKL', 'Libacao'),
  ('PH-AKL-MADALAG', 'PH-AKL', 'Madalag'),
  ('PH-AKL-MAKATO', 'PH-AKL', 'Makato'),
  ('PH-AKL-MALAY', 'PH-AKL', 'Malay'),
  ('PH-AKL-MALINAO', 'PH-AKL', 'Malinao'),
  ('PH-AKL-NABAS', 'PH-AKL', 'Nabas'),
  ('PH-AKL-NEW-WASHINGTON', 'PH-AKL', 'New Washington'),
  ('PH-AKL-NUMANCIA', 'PH-AKL', 'Numancia'),
  ('PH-AKL-TANGALAN', 'PH-AKL', 'Tangalan'),
  ('PH-ALB-BACACAY', 'PH-ALB', 'Bacacay'),
  ('PH-ALB-CAMALIG', 'PH-ALB', 'Camalig'),
  ('PH-ALB-DARAGA-LOCSIN', 'PH-ALB', 'Daraga (Locsin)'),
  ('PH-ALB-GUINOBATAN', 'PH-ALB', 'Guinobatan'),
  ('PH-ALB-JOVELLAR', 'PH-ALB', 'Jovellar'),
  ('PH-ALB-LEGAZPI-CITY', 'PH-ALB', 'Legazpi City'),
  ('PH-ALB-LIBON', 'PH-ALB', 'Libon'),
  ('PH-ALB-LIGAO-CITY', 'PH-ALB', 'Ligao City'),
  ('PH-ALB-MALILIPOT', 'PH-ALB', 'Malilipot'),
  ('PH-ALB-MALINAO', 'PH-ALB', 'Malinao'),
  ('PH-ALB-MANITO', 'PH-ALB', 'Manito'),
  ('PH-ALB-OAS', 'PH-ALB', 'Oas'),
  ('PH-ALB-PIO-DURAN', 'PH-ALB', 'Pio Duran'),
  ('PH-ALB-POLANGUI', 'PH-ALB', 'Polangui'),
  ('PH-ALB-RAPU-RAPU', 'PH-ALB', 'Rapu-Rapu'),
  ('PH-ALB-SANTO-DOMINGO-LIBOG', 'PH-ALB', 'Santo Domingo (Libog)'),
  ('PH-ALB-TABACO-CITY', 'PH-ALB', 'Tabaco City'),
  ('PH-ALB-TIWI', 'PH-ALB', 'Tiwi'),
  ('PH-ANT-ANINI-Y', 'PH-ANT', 'Anini-Y'),
  ('PH-ANT-BARBAZA', 'PH-ANT', 'Barbaza'),
  ('PH-ANT-BELISON', 'PH-ANT', 'Belison'),
  ('PH-ANT-BUGASONG', 'PH-ANT', 'Bugasong'),
  ('PH-ANT-CALUYA', 'PH-ANT', 'Caluya'),
  ('PH-ANT-CULASI', 'PH-ANT', 'Culasi'),
  ('PH-ANT-HAMTIC', 'PH-ANT', 'Hamtic'),
  ('PH-ANT-LAUA-AN', 'PH-ANT', 'Laua-An'),
  ('PH-ANT-LIBERTAD', 'PH-ANT', 'Libertad'),
  ('PH-ANT-PANDAN', 'PH-ANT', 'Pandan'),
  ('PH-ANT-PATNONGON', 'PH-ANT', 'Patnongon'),
  ('PH-ANT-SAN-JOSE', 'PH-ANT', 'San Jose'),
  ('PH-ANT-SAN-REMIGIO', 'PH-ANT', 'San Remigio'),
  ('PH-ANT-SEBASTE', 'PH-ANT', 'Sebaste'),
  ('PH-ANT-SIBALOM', 'PH-ANT', 'Sibalom'),
  ('PH-ANT-TIBIAO', 'PH-ANT', 'Tibiao'),
  ('PH-ANT-TOBIAS-FORNIER-DAO', 'PH-ANT', 'Tobias Fornier (Dao)'),
  ('PH-ANT-VALDERRAMA', 'PH-ANT', 'Valderrama'),
  ('PH-APA-CALANASAN-BAYAG', 'PH-APA', 'Calanasan (Bayag)'),
  ('PH-APA-CONNER', 'PH-APA', 'Conner'),
  ('PH-APA-FLORA', 'PH-APA', 'Flora'),
  ('PH-APA-KABUGAO', 'PH-APA', 'Kabugao'),
  ('PH-APA-LUNA', 'PH-APA', 'Luna'),
  ('PH-APA-PUDTOL', 'PH-APA', 'Pudtol'),
  ('PH-APA-SANTA-MARCELA', 'PH-APA', 'Santa Marcela'),
  ('PH-AUR-BALER', 'PH-AUR', 'Baler'),
  ('PH-AUR-CASIGURAN', 'PH-AUR', 'Casiguran'),
  ('PH-AUR-DILASAG', 'PH-AUR', 'Dilasag'),
  ('PH-AUR-DINALUNGAN', 'PH-AUR', 'Dinalungan'),
  ('PH-AUR-DINGALAN', 'PH-AUR', 'Dingalan'),
  ('PH-AUR-DIPACULAO', 'PH-AUR', 'Dipaculao'),
  ('PH-AUR-MARIA-AURORA', 'PH-AUR', 'Maria Aurora'),
  ('PH-AUR-SAN-LUIS', 'PH-AUR', 'San Luis'),
  ('PH-BAN-ABUCAY', 'PH-BAN', 'Abucay'),
  ('PH-BAN-BAGAC', 'PH-BAN', 'Bagac'),
  ('PH-BAN-BALANGA-CITY', 'PH-BAN', 'Balanga City'),
  ('PH-BAN-DINALUPIHAN', 'PH-BAN', 'Dinalupihan'),
  ('PH-BAN-HERMOSA', 'PH-BAN', 'Hermosa'),
  ('PH-BAN-LIMAY', 'PH-BAN', 'Limay'),
  ('PH-BAN-MARIVELES', 'PH-BAN', 'Mariveles'),
  ('PH-BAN-MORONG', 'PH-BAN', 'Morong'),
  ('PH-BAN-ORANI', 'PH-BAN', 'Orani'),
  ('PH-BAN-ORION', 'PH-BAN', 'Orion'),
  ('PH-BAN-PILAR', 'PH-BAN', 'Pilar'),
  ('PH-BAN-SAMAL', 'PH-BAN', 'Samal'),
  ('PH-BAS-AKBAR', 'PH-BAS', 'Akbar'),
  ('PH-BAS-AL-BARKA', 'PH-BAS', 'Al-Barka'),
  ('PH-BAS-HADJI-MOHAMMAD-AJUL', 'PH-BAS', 'Hadji Mohammad Ajul'),
  ('PH-BAS-HADJI-MUHTAMAD', 'PH-BAS', 'Hadji Muhtamad'),
  ('PH-BAS-LAMITAN-CITY', 'PH-BAS', 'Lamitan City'),
  ('PH-BAS-LANTAWAN', 'PH-BAS', 'Lantawan'),
  ('PH-BAS-MALUSO', 'PH-BAS', 'Maluso'),
  ('PH-BAS-SUMISIP', 'PH-BAS', 'Sumisip'),
  ('PH-BAS-TABUAN-LASA', 'PH-BAS', 'Tabuan-Lasa'),
  ('PH-BAS-TIPO-TIPO', 'PH-BAS', 'Tipo-Tipo'),
  ('PH-BAS-TUBURAN', 'PH-BAS', 'Tuburan'),
  ('PH-BAS-UNGKAYA-PUKAN', 'PH-BAS', 'Ungkaya Pukan'),
  ('PH-BEN-ATOK', 'PH-BEN', 'Atok'),
  ('PH-BEN-BAGUIO-CITY', 'PH-BEN', 'Baguio City'),
  ('PH-BEN-BAKUN', 'PH-BEN', 'Bakun'),
  ('PH-BEN-BOKOD', 'PH-BEN', 'Bokod'),
  ('PH-BEN-BUGUIAS', 'PH-BEN', 'Buguias'),
  ('PH-BEN-ITOGON', 'PH-BEN', 'Itogon'),
  ('PH-BEN-KABAYAN', 'PH-BEN', 'Kabayan'),
  ('PH-BEN-KAPANGAN', 'PH-BEN', 'Kapangan'),
  ('PH-BEN-KIBUNGAN', 'PH-BEN', 'Kibungan'),
  ('PH-BEN-LA-TRINIDAD', 'PH-BEN', 'La Trinidad'),
  ('PH-BEN-MANKAYAN', 'PH-BEN', 'Mankayan'),
  ('PH-BEN-SABLAN', 'PH-BEN', 'Sablan'),
  ('PH-BEN-TUBA', 'PH-BEN', 'Tuba'),
  ('PH-BEN-TUBLAY', 'PH-BEN', 'Tublay'),
  ('PH-BIL-ALMERIA', 'PH-BIL', 'Almeria'),
  ('PH-BIL-BILIRAN', 'PH-BIL', 'Biliran'),
  ('PH-BIL-CABUCGAYAN', 'PH-BIL', 'Cabucgayan'),
  ('PH-BIL-CAIBIRAN', 'PH-BIL', 'Caibiran'),
  ('PH-BIL-CULABA', 'PH-BIL', 'Culaba'),
  ('PH-BIL-KAWAYAN', 'PH-BIL', 'Kawayan'),
  ('PH-BIL-MARIPIPI', 'PH-BIL', 'Maripipi'),
  ('PH-BIL-NAVAL', 'PH-BIL', 'Naval'),
  ('PH-BTG-AGONCILLO', 'PH-BTG', 'Agoncillo'),
  ('PH-BTG-ALITAGTAG', 'PH-BTG', 'Alitagtag'),
  ('PH-BTG-BALAYAN', 'PH-BTG', 'Balayan'),
  ('PH-BTG-BALETE', 'PH-BTG', 'Balete'),
  ('PH-BTG-BATANGAS-CITY', 'PH-BTG', 'Batangas City'),
  ('PH-BTG-BAUAN', 'PH-BTG', 'Bauan'),
  ('PH-BTG-CALACA', 'PH-BTG', 'Calaca'),
  ('PH-BTG-CALATAGAN', 'PH-BTG', 'Calatagan'),
  ('PH-BTG-CUENCA', 'PH-BTG', 'Cuenca'),
  ('PH-BTG-IBAAN', 'PH-BTG', 'Ibaan'),
  ('PH-BTG-LAUREL', 'PH-BTG', 'Laurel'),
  ('PH-BTG-LEMERY', 'PH-BTG', 'Lemery'),
  ('PH-BTG-LIAN', 'PH-BTG', 'Lian'),
  ('PH-BTG-LIPA-CITY', 'PH-BTG', 'Lipa City'),
  ('PH-BTG-LOBO', 'PH-BTG', 'Lobo'),
  ('PH-BTG-MABINI', 'PH-BTG', 'Mabini'),
  ('PH-BTG-MALVAR', 'PH-BTG', 'Malvar'),
  ('PH-BTG-MATAASNAKAHOY', 'PH-BTG', 'Mataasnakahoy'),
  ('PH-BTG-NASUGBU', 'PH-BTG', 'Nasugbu'),
  ('PH-BTG-PADRE-GARCIA', 'PH-BTG', 'Padre Garcia'),
  ('PH-BTG-ROSARIO', 'PH-BTG', 'Rosario'),
  ('PH-BTG-SAN-JOSE', 'PH-BTG', 'San Jose'),
  ('PH-BTG-SAN-JUAN', 'PH-BTG', 'San Juan'),
  ('PH-BTG-SAN-LUIS', 'PH-BTG', 'San Luis'),
  ('PH-BTG-SAN-NICOLAS', 'PH-BTG', 'San Nicolas'),
  ('PH-BTG-SAN-PASCUAL', 'PH-BTG', 'San Pascual'),
  ('PH-BTG-SANTA-TERESITA', 'PH-BTG', 'Santa Teresita'),
  ('PH-BTG-SANTO-TOMAS', 'PH-BTG', 'Santo Tomas'),
  ('PH-BTG-TAAL', 'PH-BTG', 'Taal'),
  ('PH-BTG-TALISAY', 'PH-BTG', 'Talisay'),
  ('PH-BTG-TANAUAN-CITY', 'PH-BTG', 'Tanauan City'),
  ('PH-BTG-TAYSAN', 'PH-BTG', 'Taysan'),
  ('PH-BTG-TINGLOY', 'PH-BTG', 'Tingloy'),
  ('PH-BTG-TUY', 'PH-BTG', 'Tuy'),
  ('PH-BTN-BASCO', 'PH-BTN', 'Basco'),
  ('PH-BTN-ITBAYAT', 'PH-BTN', 'Itbayat'),
  ('PH-BTN-IVANA', 'PH-BTN', 'Ivana'),
  ('PH-BTN-MAHATAO', 'PH-BTN', 'Mahatao'),
  ('PH-BTN-SABTANG', 'PH-BTN', 'Sabtang'),
  ('PH-BTN-UYUGAN', 'PH-BTN', 'Uyugan'),
  ('PH-BUK-BAUNGON', 'PH-BUK', 'Baungon'),
  ('PH-BUK-CABANGLASAN', 'PH-BUK', 'Cabanglasan'),
  ('PH-BUK-DAMULOG', 'PH-BUK', 'Damulog'),
  ('PH-BUK-DANGCAGAN', 'PH-BUK', 'Dangcagan'),
  ('PH-BUK-DON-CARLOS', 'PH-BUK', 'Don Carlos'),
  ('PH-BUK-IMPASUG-ONG', 'PH-BUK', 'Impasug-Ong'),
  ('PH-BUK-KADINGILAN', 'PH-BUK', 'Kadingilan'),
  ('PH-BUK-KALILANGAN', 'PH-BUK', 'Kalilangan'),
  ('PH-BUK-KIBAWE', 'PH-BUK', 'Kibawe'),
  ('PH-BUK-KITAOTAO', 'PH-BUK', 'Kitaotao'),
  ('PH-BUK-LANTAPAN', 'PH-BUK', 'Lantapan'),
  ('PH-BUK-LIBONA', 'PH-BUK', 'Libona'),
  ('PH-BUK-MALAYBALAY-CITY', 'PH-BUK', 'Malaybalay City'),
  ('PH-BUK-MALITBOG', 'PH-BUK', 'Malitbog'),
  ('PH-BUK-MANOLO-FORTICH', 'PH-BUK', 'Manolo Fortich'),
  ('PH-BUK-MARAMAG', 'PH-BUK', 'Maramag'),
  ('PH-BUK-PANGANTUCAN', 'PH-BUK', 'Pangantucan'),
  ('PH-BUK-QUEZON', 'PH-BUK', 'Quezon'),
  ('PH-BUK-SAN-FERNANDO', 'PH-BUK', 'San Fernando'),
  ('PH-BUK-SUMILAO', 'PH-BUK', 'Sumilao'),
  ('PH-BUK-TALAKAG', 'PH-BUK', 'Talakag'),
  ('PH-BUK-VALENCIA-CITY', 'PH-BUK', 'Valencia City'),
  ('PH-BUL-ANGAT', 'PH-BUL', 'Angat'),
  ('PH-BUL-BALAGTAS-BIGAA', 'PH-BUL', 'Balagtas (Bigaa)'),
  ('PH-BUL-BALIUAG', 'PH-BUL', 'Baliuag'),
  ('PH-BUL-BOCAUE', 'PH-BUL', 'Bocaue'),
  ('PH-BUL-BULACAN', 'PH-BUL', 'Bulacan'),
  ('PH-BUL-BUSTOS', 'PH-BUL', 'Bustos'),
  ('PH-BUL-CALUMPIT', 'PH-BUL', 'Calumpit'),
  ('PH-BUL-DONA-REMEDIOS-TRINIDAD', 'PH-BUL', 'Doña Remedios Trinidad'),
  ('PH-BUL-GUIGUINTO', 'PH-BUL', 'Guiguinto'),
  ('PH-BUL-HAGONOY', 'PH-BUL', 'Hagonoy'),
  ('PH-BUL-MALOLOS-CITY', 'PH-BUL', 'Malolos City'),
  ('PH-BUL-MARILAO', 'PH-BUL', 'Marilao'),
  ('PH-BUL-MEYCAUAYAN-CITY', 'PH-BUL', 'Meycauayan City'),
  ('PH-BUL-NORZAGARAY', 'PH-BUL', 'Norzagaray'),
  ('PH-BUL-OBANDO', 'PH-BUL', 'Obando'),
  ('PH-BUL-PANDI', 'PH-BUL', 'Pandi'),
  ('PH-BUL-PAOMBONG', 'PH-BUL', 'Paombong'),
  ('PH-BUL-PLARIDEL', 'PH-BUL', 'Plaridel'),
  ('PH-BUL-PULILAN', 'PH-BUL', 'Pulilan'),
  ('PH-BUL-SAN-ILDEFONSO', 'PH-BUL', 'San Ildefonso'),
  ('PH-BUL-SAN-JOSE-DEL-MONTE-CITY', 'PH-BUL', 'San Jose Del Monte City'),
  ('PH-BUL-SAN-MIGUEL', 'PH-BUL', 'San Miguel'),
  ('PH-BUL-SAN-RAFAEL', 'PH-BUL', 'San Rafael'),
  ('PH-BUL-SANTA-MARIA', 'PH-BUL', 'Santa Maria'),
  ('PH-CAG-ABULUG', 'PH-CAG', 'Abulug'),
  ('PH-CAG-ALCALA', 'PH-CAG', 'Alcala'),
  ('PH-CAG-ALLACAPAN', 'PH-CAG', 'Allacapan'),
  ('PH-CAG-AMULUNG', 'PH-CAG', 'Amulung'),
  ('PH-CAG-APARRI', 'PH-CAG', 'Aparri'),
  ('PH-CAG-BAGGAO', 'PH-CAG', 'Baggao'),
  ('PH-CAG-BALLESTEROS', 'PH-CAG', 'Ballesteros'),
  ('PH-CAG-BUGUEY', 'PH-CAG', 'Buguey'),
  ('PH-CAG-CALAYAN', 'PH-CAG', 'Calayan'),
  ('PH-CAG-CAMALANIUGAN', 'PH-CAG', 'Camalaniugan'),
  ('PH-CAG-CLAVERIA', 'PH-CAG', 'Claveria'),
  ('PH-CAG-ENRILE', 'PH-CAG', 'Enrile'),
  ('PH-CAG-GATTARAN', 'PH-CAG', 'Gattaran'),
  ('PH-CAG-GONZAGA', 'PH-CAG', 'Gonzaga'),
  ('PH-CAG-IGUIG', 'PH-CAG', 'Iguig'),
  ('PH-CAG-LAL-LO', 'PH-CAG', 'Lal-Lo'),
  ('PH-CAG-LASAM', 'PH-CAG', 'Lasam'),
  ('PH-CAG-PAMPLONA', 'PH-CAG', 'Pamplona'),
  ('PH-CAG-PENABLANCA', 'PH-CAG', 'Peñablanca'),
  ('PH-CAG-PIAT', 'PH-CAG', 'Piat'),
  ('PH-CAG-RIZAL', 'PH-CAG', 'Rizal'),
  ('PH-CAG-SANCHEZ-MIRA', 'PH-CAG', 'Sanchez-Mira'),
  ('PH-CAG-SANTA-ANA', 'PH-CAG', 'Santa Ana'),
  ('PH-CAG-SANTA-PRAXEDES', 'PH-CAG', 'Santa Praxedes'),
  ('PH-CAG-SANTA-TERESITA', 'PH-CAG', 'Santa Teresita'),
  ('PH-CAG-SANTO-NINO-FAIRE', 'PH-CAG', 'Santo Niño (Faire)'),
  ('PH-CAG-SOLANA', 'PH-CAG', 'Solana'),
  ('PH-CAG-TUAO', 'PH-CAG', 'Tuao'),
  ('PH-CAG-TUGUEGARAO-CITY', 'PH-CAG', 'Tuguegarao City'),
  ('PH-CAM-CATARMAN', 'PH-CAM', 'Catarman'),
  ('PH-CAM-GUINSILIBAN', 'PH-CAM', 'Guinsiliban'),
  ('PH-CAM-MAHINOG', 'PH-CAM', 'Mahinog'),
  ('PH-CAM-MAMBAJAO', 'PH-CAM', 'Mambajao'),
  ('PH-CAM-SAGAY', 'PH-CAM', 'Sagay'),
  ('PH-CAN-BASUD', 'PH-CAN', 'Basud'),
  ('PH-CAN-CAPALONGA', 'PH-CAN', 'Capalonga'),
  ('PH-CAN-DAET', 'PH-CAN', 'Daet'),
  ('PH-CAN-JOSE-PANGANIBAN', 'PH-CAN', 'Jose Panganiban'),
  ('PH-CAN-LABO', 'PH-CAN', 'Labo'),
  ('PH-CAN-MERCEDES', 'PH-CAN', 'Mercedes'),
  ('PH-CAN-PARACALE', 'PH-CAN', 'Paracale'),
  ('PH-CAN-SAN-LORENZO-RUIZ-IMELDA', 'PH-CAN', 'San Lorenzo Ruiz (Imelda)'),
  ('PH-CAN-SAN-VICENTE', 'PH-CAN', 'San Vicente'),
  ('PH-CAN-SANTA-ELENA', 'PH-CAN', 'Santa Elena'),
  ('PH-CAN-TALISAY', 'PH-CAN', 'Talisay'),
  ('PH-CAN-VINZONS', 'PH-CAN', 'Vinzons'),
  ('PH-CAP-CUARTERO', 'PH-CAP', 'Cuartero'),
  ('PH-CAP-DAO', 'PH-CAP', 'Dao'),
  ('PH-CAP-DUMALAG', 'PH-CAP', 'Dumalag'),
  ('PH-CAP-DUMARAO', 'PH-CAP', 'Dumarao'),
  ('PH-CAP-IVISAN', 'PH-CAP', 'Ivisan'),
  ('PH-CAP-JAMINDAN', 'PH-CAP', 'Jamindan'),
  ('PH-CAP-MA-AYON', 'PH-CAP', 'Ma-Ayon'),
  ('PH-CAP-MAMBUSAO', 'PH-CAP', 'Mambusao'),
  ('PH-CAP-PANAY', 'PH-CAP', 'Panay'),
  ('PH-CAP-PANITAN', 'PH-CAP', 'Panitan'),
  ('PH-CAP-PILAR', 'PH-CAP', 'Pilar'),
  ('PH-CAP-PONTEVEDRA', 'PH-CAP', 'Pontevedra'),
  ('PH-CAP-PRESIDENT-ROXAS', 'PH-CAP', 'President Roxas'),
  ('PH-CAP-ROXAS-CITY', 'PH-CAP', 'Roxas City'),
  ('PH-CAP-SAPI-AN', 'PH-CAP', 'Sapi-An'),
  ('PH-CAP-SIGMA', 'PH-CAP', 'Sigma'),
  ('PH-CAP-TAPAZ', 'PH-CAP', 'Tapaz'),
  ('PH-CAS-BAAO', 'PH-CAS', 'Baao'),
  ('PH-CAS-BALATAN', 'PH-CAS', 'Balatan'),
  ('PH-CAS-BATO', 'PH-CAS', 'Bato'),
  ('PH-CAS-BOMBON', 'PH-CAS', 'Bombon'),
  ('PH-CAS-BUHI', 'PH-CAS', 'Buhi'),
  ('PH-CAS-BULA', 'PH-CAS', 'Bula'),
  ('PH-CAS-CABUSAO', 'PH-CAS', 'Cabusao'),
  ('PH-CAS-CALABANGA', 'PH-CAS', 'Calabanga'),
  ('PH-CAS-CAMALIGAN', 'PH-CAS', 'Camaligan'),
  ('PH-CAS-CANAMAN', 'PH-CAS', 'Canaman'),
  ('PH-CAS-CARAMOAN', 'PH-CAS', 'Caramoan'),
  ('PH-CAS-DEL-GALLEGO', 'PH-CAS', 'Del Gallego'),
  ('PH-CAS-GAINZA', 'PH-CAS', 'Gainza'),
  ('PH-CAS-GARCHITORENA', 'PH-CAS', 'Garchitorena'),
  ('PH-CAS-GOA', 'PH-CAS', 'Goa'),
  ('PH-CAS-IRIGA-CITY', 'PH-CAS', 'Iriga City'),
  ('PH-CAS-LAGONOY', 'PH-CAS', 'Lagonoy'),
  ('PH-CAS-LIBMANAN', 'PH-CAS', 'Libmanan'),
  ('PH-CAS-LUPI', 'PH-CAS', 'Lupi'),
  ('PH-CAS-MAGARAO', 'PH-CAS', 'Magarao'),
  ('PH-CAS-MILAOR', 'PH-CAS', 'Milaor'),
  ('PH-CAS-MINALABAC', 'PH-CAS', 'Minalabac'),
  ('PH-CAS-NABUA', 'PH-CAS', 'Nabua'),
  ('PH-CAS-NAGA-CITY', 'PH-CAS', 'Naga City'),
  ('PH-CAS-OCAMPO', 'PH-CAS', 'Ocampo'),
  ('PH-CAS-PAMPLONA', 'PH-CAS', 'Pamplona'),
  ('PH-CAS-PASACAO', 'PH-CAS', 'Pasacao'),
  ('PH-CAS-PILI', 'PH-CAS', 'Pili'),
  ('PH-CAS-PRESENTACION-PARUBCAN', 'PH-CAS', 'Presentacion (Parubcan)'),
  ('PH-CAS-RAGAY', 'PH-CAS', 'Ragay'),
  ('PH-CAS-SAGNAY', 'PH-CAS', 'Sagñay'),
  ('PH-CAS-SAN-FERNANDO', 'PH-CAS', 'San Fernando'),
  ('PH-CAS-SAN-JOSE', 'PH-CAS', 'San Jose'),
  ('PH-CAS-SIPOCOT', 'PH-CAS', 'Sipocot'),
  ('PH-CAS-SIRUMA', 'PH-CAS', 'Siruma'),
  ('PH-CAS-TIGAON', 'PH-CAS', 'Tigaon'),
  ('PH-CAS-TINAMBAC', 'PH-CAS', 'Tinambac'),
  ('PH-CAT-BAGAMANOC', 'PH-CAT', 'Bagamanoc'),
  ('PH-CAT-BARAS', 'PH-CAT', 'Baras'),
  ('PH-CAT-BATO', 'PH-CAT', 'Bato'),
  ('PH-CAT-CARAMORAN', 'PH-CAT', 'Caramoran'),
  ('PH-CAT-GIGMOTO', 'PH-CAT', 'Gigmoto'),
  ('PH-CAT-PANDAN', 'PH-CAT', 'Pandan'),
  ('PH-CAT-PANGANIBAN-PAYO', 'PH-CAT', 'Panganiban (Payo)'),
  ('PH-CAT-SAN-ANDRES-CALOLBON', 'PH-CAT', 'San Andres (Calolbon)'),
  ('PH-CAT-SAN-MIGUEL', 'PH-CAT', 'San Miguel'),
  ('PH-CAT-VIGA', 'PH-CAT', 'Viga'),
  ('PH-CAT-VIRAC', 'PH-CAT', 'Virac'),
  ('PH-CAV-ALFONSO', 'PH-CAV', 'Alfonso'),
  ('PH-CAV-AMADEO', 'PH-CAV', 'Amadeo'),
  ('PH-CAV-BACOOR-CITY', 'PH-CAV', 'Bacoor City'),
  ('PH-CAV-CARMONA', 'PH-CAV', 'Carmona'),
  ('PH-CAV-CAVITE-CITY', 'PH-CAV', 'Cavite City'),
  ('PH-CAV-DASMARINAS-CITY', 'PH-CAV', 'Dasmariñas City'),
  ('PH-CAV-GEN-MARIANO-ALVAREZ', 'PH-CAV', 'Gen. Mariano Alvarez'),
  ('PH-CAV-GENERAL-EMILIO-AGUINALDO', 'PH-CAV', 'General Emilio Aguinaldo'),
  ('PH-CAV-GENERAL-TRIAS', 'PH-CAV', 'General Trias'),
  ('PH-CAV-IMUS-CITY', 'PH-CAV', 'Imus City'),
  ('PH-CAV-INDANG', 'PH-CAV', 'Indang'),
  ('PH-CAV-KAWIT', 'PH-CAV', 'Kawit'),
  ('PH-CAV-MAGALLANES', 'PH-CAV', 'Magallanes'),
  ('PH-CAV-MARAGONDON', 'PH-CAV', 'Maragondon'),
  ('PH-CAV-MENDEZ-MENDEZ-NUNEZ', 'PH-CAV', 'Mendez (Mendez-Nuñez)'),
  ('PH-CAV-NAIC', 'PH-CAV', 'Naic'),
  ('PH-CAV-NOVELETA', 'PH-CAV', 'Noveleta'),
  ('PH-CAV-ROSARIO', 'PH-CAV', 'Rosario'),
  ('PH-CAV-SILANG', 'PH-CAV', 'Silang'),
  ('PH-CAV-TAGAYTAY-CITY', 'PH-CAV', 'Tagaytay City'),
  ('PH-CAV-TANZA', 'PH-CAV', 'Tanza'),
  ('PH-CAV-TERNATE', 'PH-CAV', 'Ternate'),
  ('PH-CAV-TRECE-MARTIRES-CITY', 'PH-CAV', 'Trece Martires City'),
  ('PH-CEB-ALCANTARA', 'PH-CEB', 'Alcantara'),
  ('PH-CEB-ALCOY', 'PH-CEB', 'Alcoy'),
  ('PH-CEB-ALEGRIA', 'PH-CEB', 'Alegria'),
  ('PH-CEB-ALOGUINSAN', 'PH-CEB', 'Aloguinsan'),
  ('PH-CEB-ARGAO', 'PH-CEB', 'Argao'),
  ('PH-CEB-ASTURIAS', 'PH-CEB', 'Asturias'),
  ('PH-CEB-BADIAN', 'PH-CEB', 'Badian'),
  ('PH-CEB-BALAMBAN', 'PH-CEB', 'Balamban'),
  ('PH-CEB-BANTAYAN', 'PH-CEB', 'Bantayan'),
  ('PH-CEB-BARILI', 'PH-CEB', 'Barili'),
  ('PH-CEB-BOGO-CITY', 'PH-CEB', 'Bogo City'),
  ('PH-CEB-BOLJOON', 'PH-CEB', 'Boljoon'),
  ('PH-CEB-BORBON', 'PH-CEB', 'Borbon'),
  ('PH-CEB-CARCAR-CITY', 'PH-CEB', 'Carcar City'),
  ('PH-CEB-CARMEN', 'PH-CEB', 'Carmen'),
  ('PH-CEB-CATMON', 'PH-CEB', 'Catmon'),
  ('PH-CEB-CEBU-CITY', 'PH-CEB', 'Cebu City'),
  ('PH-CEB-COMPOSTELA', 'PH-CEB', 'Compostela'),
  ('PH-CEB-CONSOLACION', 'PH-CEB', 'Consolacion'),
  ('PH-CEB-CORDOVA', 'PH-CEB', 'Cordova'),
  ('PH-CEB-DAANBANTAYAN', 'PH-CEB', 'Daanbantayan'),
  ('PH-CEB-DALAGUETE', 'PH-CEB', 'Dalaguete'),
  ('PH-CEB-DANAO-CITY', 'PH-CEB', 'Danao City'),
  ('PH-CEB-DUMANJUG', 'PH-CEB', 'Dumanjug'),
  ('PH-CEB-GINATILAN', 'PH-CEB', 'Ginatilan'),
  ('PH-CEB-LAPU-LAPU-CITY-OPON', 'PH-CEB', 'Lapu-Lapu City (Opon)'),
  ('PH-CEB-LILOAN', 'PH-CEB', 'Liloan'),
  ('PH-CEB-MADRIDEJOS', 'PH-CEB', 'Madridejos'),
  ('PH-CEB-MALABUYOC', 'PH-CEB', 'Malabuyoc'),
  ('PH-CEB-MANDAUE-CITY', 'PH-CEB', 'Mandaue City'),
  ('PH-CEB-MEDELLIN', 'PH-CEB', 'Medellin'),
  ('PH-CEB-MINGLANILLA', 'PH-CEB', 'Minglanilla'),
  ('PH-CEB-MOALBOAL', 'PH-CEB', 'Moalboal'),
  ('PH-CEB-NAGA-CITY', 'PH-CEB', 'Naga City'),
  ('PH-CEB-OSLOB', 'PH-CEB', 'Oslob'),
  ('PH-CEB-PILAR', 'PH-CEB', 'Pilar'),
  ('PH-CEB-PINAMUNGAHAN', 'PH-CEB', 'Pinamungahan'),
  ('PH-CEB-PORO', 'PH-CEB', 'Poro'),
  ('PH-CEB-RONDA', 'PH-CEB', 'Ronda'),
  ('PH-CEB-SAMBOAN', 'PH-CEB', 'Samboan'),
  ('PH-CEB-SAN-FERNANDO', 'PH-CEB', 'San Fernando'),
  ('PH-CEB-SAN-FRANCISCO', 'PH-CEB', 'San Francisco'),
  ('PH-CEB-SAN-REMIGIO', 'PH-CEB', 'San Remigio'),
  ('PH-CEB-SANTA-FE', 'PH-CEB', 'Santa Fe'),
  ('PH-CEB-SANTANDER', 'PH-CEB', 'Santander'),
  ('PH-CEB-SIBONGA', 'PH-CEB', 'Sibonga'),
  ('PH-CEB-SOGOD', 'PH-CEB', 'Sogod'),
  ('PH-CEB-TABOGON', 'PH-CEB', 'Tabogon'),
  ('PH-CEB-TABUELAN', 'PH-CEB', 'Tabuelan'),
  ('PH-CEB-TALISAY-CITY', 'PH-CEB', 'Talisay City'),
  ('PH-CEB-TOLEDO-CITY', 'PH-CEB', 'Toledo City'),
  ('PH-CEB-TUBURAN', 'PH-CEB', 'Tuburan'),
  ('PH-CEB-TUDELA', 'PH-CEB', 'Tudela'),
  ('PH-COM-COMPOSTELA', 'PH-COM', 'Compostela'),
  ('PH-COM-LAAK-SAN-VICENTE', 'PH-COM', 'Laak (San Vicente)'),
  ('PH-COM-MABINI-DONA-ALICIA', 'PH-COM', 'Mabini (Doña Alicia)'),
  ('PH-COM-MACO', 'PH-COM', 'Maco'),
  ('PH-COM-MARAGUSAN-SAN-MARIANO', 'PH-COM', 'Maragusan (San Mariano)'),
  ('PH-COM-MAWAB', 'PH-COM', 'Mawab'),
  ('PH-COM-MONKAYO', 'PH-COM', 'Monkayo'),
  ('PH-COM-MONTEVISTA', 'PH-COM', 'Montevista'),
  ('PH-COM-NABUNTURAN', 'PH-COM', 'Nabunturan'),
  ('PH-COM-NEW-BATAAN', 'PH-COM', 'New Bataan'),
  ('PH-COM-PANTUKAN', 'PH-COM', 'Pantukan'),
  ('PH-DAO-BAGANGA', 'PH-DAO', 'Baganga'),
  ('PH-DAO-BANAYBANAY', 'PH-DAO', 'Banaybanay'),
  ('PH-DAO-BOSTON', 'PH-DAO', 'Boston'),
  ('PH-DAO-CARAGA', 'PH-DAO', 'Caraga'),
  ('PH-DAO-CATEEL', 'PH-DAO', 'Cateel'),
  ('PH-DAO-GOVERNOR-GENEROSO', 'PH-DAO', 'Governor Generoso'),
  ('PH-DAO-LUPON', 'PH-DAO', 'Lupon'),
  ('PH-DAO-MANAY', 'PH-DAO', 'Manay'),
  ('PH-DAO-MATI-CITY', 'PH-DAO', 'Mati City'),
  ('PH-DAO-SAN-ISIDRO', 'PH-DAO', 'San Isidro'),
  ('PH-DAO-TARRAGONA', 'PH-DAO', 'Tarragona'),
  ('PH-DAS-BANSALAN', 'PH-DAS', 'Bansalan'),
  ('PH-DAS-DAVAO-CITY', 'PH-DAS', 'Davao City'),
  ('PH-DAS-DIGOS-CITY', 'PH-DAS', 'Digos City'),
  ('PH-DAS-HAGONOY', 'PH-DAS', 'Hagonoy'),
  ('PH-DAS-KIBLAWAN', 'PH-DAS', 'Kiblawan'),
  ('PH-DAS-MAGSAYSAY', 'PH-DAS', 'Magsaysay'),
  ('PH-DAS-MALALAG', 'PH-DAS', 'Malalag'),
  ('PH-DAS-MATANAO', 'PH-DAS', 'Matanao'),
  ('PH-DAS-PADADA', 'PH-DAS', 'Padada'),
  ('PH-DAS-SANTA-CRUZ', 'PH-DAS', 'Santa Cruz'),
  ('PH-DAS-SULOP', 'PH-DAS', 'Sulop'),
  ('PH-DAV-ASUNCION-SAUG', 'PH-DAV', 'Asuncion (Saug)'),
  ('PH-DAV-BRAULIO-E-DUJALI', 'PH-DAV', 'Braulio E. Dujali'),
  ('PH-DAV-CARMEN', 'PH-DAV', 'Carmen'),
  ('PH-DAV-ISLAND-GARDEN-CITY-OF-SAMAL', 'PH-DAV', 'Island Garden City Of Samal'),
  ('PH-DAV-KAPALONG', 'PH-DAV', 'Kapalong'),
  ('PH-DAV-NEW-CORELLA', 'PH-DAV', 'New Corella'),
  ('PH-DAV-PANABO-CITY', 'PH-DAV', 'Panabo City'),
  ('PH-DAV-SAN-ISIDRO', 'PH-DAV', 'San Isidro'),
  ('PH-DAV-SANTO-TOMAS', 'PH-DAV', 'Santo Tomas'),
  ('PH-DAV-TAGUM-CITY', 'PH-DAV', 'Tagum City'),
  ('PH-DAV-TALAINGOD', 'PH-DAV', 'Talaingod'),
  ('PH-DIN-BASILISA-RIZAL', 'PH-DIN', 'Basilisa (Rizal)'),
  ('PH-DIN-CAGDIANAO', 'PH-DIN', 'Cagdianao'),
  ('PH-DIN-DINAGAT', 'PH-DIN', 'Dinagat'),
  ('PH-DIN-LIBJO-ALBOR', 'PH-DIN', 'Libjo (Albor)'),
  ('PH-DIN-LORETO', 'PH-DIN', 'Loreto'),
  ('PH-DIN-SAN-JOSE', 'PH-DIN', 'San Jose'),
  ('PH-DIN-TUBAJON', 'PH-DIN', 'Tubajon'),
  ('PH-DVO-DON-MARCELINO', 'PH-DVO', 'Don Marcelino'),
  ('PH-DVO-JOSE-ABAD-SANTOS-TRINIDAD', 'PH-DVO', 'Jose Abad Santos (Trinidad)'),
  ('PH-DVO-MALITA', 'PH-DVO', 'Malita'),
  ('PH-DVO-SANTA-MARIA', 'PH-DVO', 'Santa Maria'),
  ('PH-DVO-SARANGANI', 'PH-DVO', 'Sarangani'),
  ('PH-EAS-ARTECHE', 'PH-EAS', 'Arteche'),
  ('PH-EAS-BALANGIGA', 'PH-EAS', 'Balangiga'),
  ('PH-EAS-BALANGKAYAN', 'PH-EAS', 'Balangkayan'),
  ('PH-EAS-BORONGAN-CITY', 'PH-EAS', 'Borongan City'),
  ('PH-EAS-CAN-AVID', 'PH-EAS', 'Can-Avid'),
  ('PH-EAS-DOLORES', 'PH-EAS', 'Dolores'),
  ('PH-EAS-GENERAL-MACARTHUR', 'PH-EAS', 'General Macarthur'),
  ('PH-EAS-GIPORLOS', 'PH-EAS', 'Giporlos'),
  ('PH-EAS-GUIUAN', 'PH-EAS', 'Guiuan'),
  ('PH-EAS-HERNANI', 'PH-EAS', 'Hernani'),
  ('PH-EAS-JIPAPAD', 'PH-EAS', 'Jipapad'),
  ('PH-EAS-LAWAAN', 'PH-EAS', 'Lawaan'),
  ('PH-EAS-LLORENTE', 'PH-EAS', 'Llorente'),
  ('PH-EAS-MASLOG', 'PH-EAS', 'Maslog'),
  ('PH-EAS-MAYDOLONG', 'PH-EAS', 'Maydolong'),
  ('PH-EAS-MERCEDES', 'PH-EAS', 'Mercedes'),
  ('PH-EAS-ORAS', 'PH-EAS', 'Oras'),
  ('PH-EAS-QUINAPONDAN', 'PH-EAS', 'Quinapondan'),
  ('PH-EAS-SALCEDO', 'PH-EAS', 'Salcedo'),
  ('PH-EAS-SAN-JULIAN', 'PH-EAS', 'San Julian'),
  ('PH-EAS-SAN-POLICARPO', 'PH-EAS', 'San Policarpo'),
  ('PH-EAS-SULAT', 'PH-EAS', 'Sulat'),
  ('PH-EAS-TAFT', 'PH-EAS', 'Taft'),
  ('PH-GUI-BUENAVISTA', 'PH-GUI', 'Buenavista'),
  ('PH-GUI-JORDAN', 'PH-GUI', 'Jordan'),
  ('PH-GUI-NUEVA-VALENCIA', 'PH-GUI', 'Nueva Valencia'),
  ('PH-GUI-SAN-LORENZO', 'PH-GUI', 'San Lorenzo'),
  ('PH-GUI-SIBUNAG', 'PH-GUI', 'Sibunag'),
  ('PH-IFU-AGUINALDO', 'PH-IFU', 'Aguinaldo'),
  ('PH-IFU-ALFONSO-LISTA-POTIA', 'PH-IFU', 'Alfonso Lista (Potia)'),
  ('PH-IFU-ASIPULO', 'PH-IFU', 'Asipulo'),
  ('PH-IFU-BANAUE', 'PH-IFU', 'Banaue'),
  ('PH-IFU-HINGYON', 'PH-IFU', 'Hingyon'),
  ('PH-IFU-HUNGDUAN', 'PH-IFU', 'Hungduan'),
  ('PH-IFU-KIANGAN', 'PH-IFU', 'Kiangan'),
  ('PH-IFU-LAGAWE', 'PH-IFU', 'Lagawe'),
  ('PH-IFU-LAMUT', 'PH-IFU', 'Lamut'),
  ('PH-IFU-MAYOYAO', 'PH-IFU', 'Mayoyao'),
  ('PH-IFU-TINOC', 'PH-IFU', 'Tinoc'),
  ('PH-ILI-AJUY', 'PH-ILI', 'Ajuy'),
  ('PH-ILI-ALIMODIAN', 'PH-ILI', 'Alimodian'),
  ('PH-ILI-ANILAO', 'PH-ILI', 'Anilao'),
  ('PH-ILI-BADIANGAN', 'PH-ILI', 'Badiangan'),
  ('PH-ILI-BALASAN', 'PH-ILI', 'Balasan'),
  ('PH-ILI-BANATE', 'PH-ILI', 'Banate'),
  ('PH-ILI-BAROTAC-NUEVO', 'PH-ILI', 'Barotac Nuevo'),
  ('PH-ILI-BAROTAC-VIEJO', 'PH-ILI', 'Barotac Viejo'),
  ('PH-ILI-BATAD', 'PH-ILI', 'Batad'),
  ('PH-ILI-BINGAWAN', 'PH-ILI', 'Bingawan'),
  ('PH-ILI-CABATUAN', 'PH-ILI', 'Cabatuan'),
  ('PH-ILI-CALINOG', 'PH-ILI', 'Calinog'),
  ('PH-ILI-CARLES', 'PH-ILI', 'Carles'),
  ('PH-ILI-CONCEPCION', 'PH-ILI', 'Concepcion'),
  ('PH-ILI-DINGLE', 'PH-ILI', 'Dingle'),
  ('PH-ILI-DUENAS', 'PH-ILI', 'Dueñas'),
  ('PH-ILI-DUMANGAS', 'PH-ILI', 'Dumangas'),
  ('PH-ILI-ESTANCIA', 'PH-ILI', 'Estancia'),
  ('PH-ILI-GUIMBAL', 'PH-ILI', 'Guimbal'),
  ('PH-ILI-IGBARAS', 'PH-ILI', 'Igbaras'),
  ('PH-ILI-ILOILO-CITY', 'PH-ILI', 'Iloilo City'),
  ('PH-ILI-JANIUAY', 'PH-ILI', 'Janiuay'),
  ('PH-ILI-LAMBUNAO', 'PH-ILI', 'Lambunao'),
  ('PH-ILI-LEGANES', 'PH-ILI', 'Leganes'),
  ('PH-ILI-LEMERY', 'PH-ILI', 'Lemery'),
  ('PH-ILI-LEON', 'PH-ILI', 'Leon'),
  ('PH-ILI-MAASIN', 'PH-ILI', 'Maasin'),
  ('PH-ILI-MIAGAO', 'PH-ILI', 'Miagao'),
  ('PH-ILI-MINA', 'PH-ILI', 'Mina'),
  ('PH-ILI-NEW-LUCENA', 'PH-ILI', 'New Lucena'),
  ('PH-ILI-OTON', 'PH-ILI', 'Oton'),
  ('PH-ILI-PASSI-CITY', 'PH-ILI', 'Passi City'),
  ('PH-ILI-PAVIA', 'PH-ILI', 'Pavia'),
  ('PH-ILI-POTOTAN', 'PH-ILI', 'Pototan'),
  ('PH-ILI-SAN-DIONISIO', 'PH-ILI', 'San Dionisio'),
  ('PH-ILI-SAN-ENRIQUE', 'PH-ILI', 'San Enrique'),
  ('PH-ILI-SAN-JOAQUIN', 'PH-ILI', 'San Joaquin'),
  ('PH-ILI-SAN-MIGUEL', 'PH-ILI', 'San Miguel'),
  ('PH-ILI-SAN-RAFAEL', 'PH-ILI', 'San Rafael'),
  ('PH-ILI-SANTA-BARBARA', 'PH-ILI', 'Santa Barbara'),
  ('PH-ILI-SARA', 'PH-ILI', 'Sara'),
  ('PH-ILI-TIGBAUAN', 'PH-ILI', 'Tigbauan'),
  ('PH-ILI-TUBUNGAN', 'PH-ILI', 'Tubungan'),
  ('PH-ILI-ZARRAGA', 'PH-ILI', 'Zarraga'),
  ('PH-ILN-ADAMS', 'PH-ILN', 'Adams'),
  ('PH-ILN-BACARRA', 'PH-ILN', 'Bacarra'),
  ('PH-ILN-BADOC', 'PH-ILN', 'Badoc'),
  ('PH-ILN-BANGUI', 'PH-ILN', 'Bangui'),
  ('PH-ILN-BANNA-ESPIRITU', 'PH-ILN', 'Banna (Espiritu)'),
  ('PH-ILN-BATAC-CITY', 'PH-ILN', 'Batac City'),
  ('PH-ILN-BURGOS', 'PH-ILN', 'Burgos'),
  ('PH-ILN-CARASI', 'PH-ILN', 'Carasi'),
  ('PH-ILN-CURRIMAO', 'PH-ILN', 'Currimao'),
  ('PH-ILN-DINGRAS', 'PH-ILN', 'Dingras'),
  ('PH-ILN-DUMALNEG', 'PH-ILN', 'Dumalneg'),
  ('PH-ILN-LAOAG-CITY', 'PH-ILN', 'Laoag City'),
  ('PH-ILN-MARCOS', 'PH-ILN', 'Marcos'),
  ('PH-ILN-NUEVA-ERA', 'PH-ILN', 'Nueva Era'),
  ('PH-ILN-PAGUDPUD', 'PH-ILN', 'Pagudpud'),
  ('PH-ILN-PAOAY', 'PH-ILN', 'Paoay'),
  ('PH-ILN-PASUQUIN', 'PH-ILN', 'Pasuquin'),
  ('PH-ILN-PIDDIG', 'PH-ILN', 'Piddig'),
  ('PH-ILN-PINILI', 'PH-ILN', 'Pinili'),
  ('PH-ILN-SAN-NICOLAS', 'PH-ILN', 'San Nicolas'),
  ('PH-ILN-SARRAT', 'PH-ILN', 'Sarrat'),
  ('PH-ILN-SOLSONA', 'PH-ILN', 'Solsona'),
  ('PH-ILN-VINTAR', 'PH-ILN', 'Vintar'),
  ('PH-ILS-ALILEM', 'PH-ILS', 'Alilem'),
  ('PH-ILS-BANAYOYO', 'PH-ILS', 'Banayoyo'),
  ('PH-ILS-BANTAY', 'PH-ILS', 'Bantay'),
  ('PH-ILS-BURGOS', 'PH-ILS', 'Burgos'),
  ('PH-ILS-CABUGAO', 'PH-ILS', 'Cabugao'),
  ('PH-ILS-CANDON-CITY', 'PH-ILS', 'Candon City'),
  ('PH-ILS-CAOAYAN', 'PH-ILS', 'Caoayan'),
  ('PH-ILS-CERVANTES', 'PH-ILS', 'Cervantes'),
  ('PH-ILS-GALIMUYOD', 'PH-ILS', 'Galimuyod'),
  ('PH-ILS-GREGORIO-DEL-PILAR-CONCEPCION', 'PH-ILS', 'Gregorio Del Pilar (Concepcion)'),
  ('PH-ILS-LIDLIDDA', 'PH-ILS', 'Lidlidda'),
  ('PH-ILS-MAGSINGAL', 'PH-ILS', 'Magsingal'),
  ('PH-ILS-NAGBUKEL', 'PH-ILS', 'Nagbukel'),
  ('PH-ILS-NARVACAN', 'PH-ILS', 'Narvacan'),
  ('PH-ILS-QUIRINO-ANGKAKI', 'PH-ILS', 'Quirino (Angkaki)'),
  ('PH-ILS-SALCEDO-BAUGEN', 'PH-ILS', 'Salcedo (Baugen)'),
  ('PH-ILS-SAN-EMILIO', 'PH-ILS', 'San Emilio'),
  ('PH-ILS-SAN-ESTEBAN', 'PH-ILS', 'San Esteban'),
  ('PH-ILS-SAN-ILDEFONSO', 'PH-ILS', 'San Ildefonso'),
  ('PH-ILS-SAN-JUAN-LAPOG', 'PH-ILS', 'San Juan (Lapog)'),
  ('PH-ILS-SAN-VICENTE', 'PH-ILS', 'San Vicente'),
  ('PH-ILS-SANTA', 'PH-ILS', 'Santa'),
  ('PH-ILS-SANTA-CATALINA', 'PH-ILS', 'Santa Catalina'),
  ('PH-ILS-SANTA-CRUZ', 'PH-ILS', 'Santa Cruz'),
  ('PH-ILS-SANTA-LUCIA', 'PH-ILS', 'Santa Lucia'),
  ('PH-ILS-SANTA-MARIA', 'PH-ILS', 'Santa Maria'),
  ('PH-ILS-SANTIAGO', 'PH-ILS', 'Santiago'),
  ('PH-ILS-SANTO-DOMINGO', 'PH-ILS', 'Santo Domingo'),
  ('PH-ILS-SIGAY', 'PH-ILS', 'Sigay'),
  ('PH-ILS-SINAIT', 'PH-ILS', 'Sinait'),
  ('PH-ILS-SUGPON', 'PH-ILS', 'Sugpon'),
  ('PH-ILS-SUYO', 'PH-ILS', 'Suyo'),
  ('PH-ILS-TAGUDIN', 'PH-ILS', 'Tagudin'),
  ('PH-ILS-VIGAN-CITY', 'PH-ILS', 'Vigan City'),
  ('PH-ISA-ALICIA', 'PH-ISA', 'Alicia'),
  ('PH-ISA-ANGADANAN', 'PH-ISA', 'Angadanan'),
  ('PH-ISA-AURORA', 'PH-ISA', 'Aurora'),
  ('PH-ISA-BENITO-SOLIVEN', 'PH-ISA', 'Benito Soliven'),
  ('PH-ISA-BURGOS', 'PH-ISA', 'Burgos'),
  ('PH-ISA-CABAGAN', 'PH-ISA', 'Cabagan'),
  ('PH-ISA-CABATUAN', 'PH-ISA', 'Cabatuan'),
  ('PH-ISA-CAUAYAN-CITY', 'PH-ISA', 'Cauayan City'),
  ('PH-ISA-CORDON', 'PH-ISA', 'Cordon'),
  ('PH-ISA-DELFIN-ALBANO-MAGSAYSAY', 'PH-ISA', 'Delfin Albano (Magsaysay)'),
  ('PH-ISA-DINAPIGUE', 'PH-ISA', 'Dinapigue'),
  ('PH-ISA-DIVILACAN', 'PH-ISA', 'Divilacan'),
  ('PH-ISA-ECHAGUE', 'PH-ISA', 'Echague'),
  ('PH-ISA-GAMU', 'PH-ISA', 'Gamu'),
  ('PH-ISA-ILAGAN-CITY', 'PH-ISA', 'Ilagan City'),
  ('PH-ISA-JONES', 'PH-ISA', 'Jones'),
  ('PH-ISA-LUNA', 'PH-ISA', 'Luna'),
  ('PH-ISA-MACONACON', 'PH-ISA', 'Maconacon'),
  ('PH-ISA-MALLIG', 'PH-ISA', 'Mallig'),
  ('PH-ISA-NAGUILIAN', 'PH-ISA', 'Naguilian'),
  ('PH-ISA-PALANAN', 'PH-ISA', 'Palanan'),
  ('PH-ISA-QUEZON', 'PH-ISA', 'Quezon'),
  ('PH-ISA-QUIRINO', 'PH-ISA', 'Quirino'),
  ('PH-ISA-RAMON', 'PH-ISA', 'Ramon'),
  ('PH-ISA-REINA-MERCEDES', 'PH-ISA', 'Reina Mercedes'),
  ('PH-ISA-ROXAS', 'PH-ISA', 'Roxas'),
  ('PH-ISA-SAN-AGUSTIN', 'PH-ISA', 'San Agustin'),
  ('PH-ISA-SAN-GUILLERMO', 'PH-ISA', 'San Guillermo'),
  ('PH-ISA-SAN-ISIDRO', 'PH-ISA', 'San Isidro'),
  ('PH-ISA-SAN-MANUEL', 'PH-ISA', 'San Manuel'),
  ('PH-ISA-SAN-MARIANO', 'PH-ISA', 'San Mariano'),
  ('PH-ISA-SAN-MATEO', 'PH-ISA', 'San Mateo'),
  ('PH-ISA-SAN-PABLO', 'PH-ISA', 'San Pablo'),
  ('PH-ISA-SANTA-MARIA', 'PH-ISA', 'Santa Maria'),
  ('PH-ISA-SANTIAGO-CITY', 'PH-ISA', 'Santiago City'),
  ('PH-ISA-SANTO-TOMAS', 'PH-ISA', 'Santo Tomas'),
  ('PH-ISA-TUMAUINI', 'PH-ISA', 'Tumauini'),
  ('PH-KAL-BALBALAN', 'PH-KAL', 'Balbalan'),
  ('PH-KAL-LUBUAGAN', 'PH-KAL', 'Lubuagan'),
  ('PH-KAL-PASIL', 'PH-KAL', 'Pasil'),
  ('PH-KAL-PINUKPUK', 'PH-KAL', 'Pinukpuk'),
  ('PH-KAL-RIZAL-LIWAN', 'PH-KAL', 'Rizal (Liwan)'),
  ('PH-KAL-TABUK-CITY', 'PH-KAL', 'Tabuk City'),
  ('PH-KAL-TANUDAN', 'PH-KAL', 'Tanudan'),
  ('PH-KAL-TINGLAYAN', 'PH-KAL', 'Tinglayan'),
  ('PH-LAG-ALAMINOS', 'PH-LAG', 'Alaminos'),
  ('PH-LAG-BAY', 'PH-LAG', 'Bay'),
  ('PH-LAG-BINAN-CITY', 'PH-LAG', 'Biñan City'),
  ('PH-LAG-CABUYAO-CITY', 'PH-LAG', 'Cabuyao City'),
  ('PH-LAG-CALAMBA-CITY', 'PH-LAG', 'Calamba City'),
  ('PH-LAG-CALAUAN', 'PH-LAG', 'Calauan'),
  ('PH-LAG-CAVINTI', 'PH-LAG', 'Cavinti'),
  ('PH-LAG-FAMY', 'PH-LAG', 'Famy'),
  ('PH-LAG-KALAYAAN', 'PH-LAG', 'Kalayaan'),
  ('PH-LAG-LILIW', 'PH-LAG', 'Liliw'),
  ('PH-LAG-LOS-BANOS', 'PH-LAG', 'Los Baños'),
  ('PH-LAG-LUISIANA', 'PH-LAG', 'Luisiana'),
  ('PH-LAG-LUMBAN', 'PH-LAG', 'Lumban'),
  ('PH-LAG-MABITAC', 'PH-LAG', 'Mabitac'),
  ('PH-LAG-MAGDALENA', 'PH-LAG', 'Magdalena'),
  ('PH-LAG-MAJAYJAY', 'PH-LAG', 'Majayjay'),
  ('PH-LAG-NAGCARLAN', 'PH-LAG', 'Nagcarlan'),
  ('PH-LAG-PAETE', 'PH-LAG', 'Paete'),
  ('PH-LAG-PAGSANJAN', 'PH-LAG', 'Pagsanjan'),
  ('PH-LAG-PAKIL', 'PH-LAG', 'Pakil'),
  ('PH-LAG-PANGIL', 'PH-LAG', 'Pangil'),
  ('PH-LAG-PILA', 'PH-LAG', 'Pila'),
  ('PH-LAG-RIZAL', 'PH-LAG', 'Rizal'),
  ('PH-LAG-SAN-PABLO-CITY', 'PH-LAG', 'San Pablo City'),
  ('PH-LAG-SAN-PEDRO-CITY', 'PH-LAG', 'San Pedro City'),
  ('PH-LAG-SANTA-CRUZ', 'PH-LAG', 'Santa Cruz'),
  ('PH-LAG-SANTA-MARIA', 'PH-LAG', 'Santa Maria'),
  ('PH-LAG-SANTA-ROSA-CITY', 'PH-LAG', 'Santa Rosa City'),
  ('PH-LAG-SINILOAN', 'PH-LAG', 'Siniloan'),
  ('PH-LAG-VICTORIA', 'PH-LAG', 'Victoria'),
  ('PH-LAN-BACOLOD', 'PH-LAN', 'Bacolod'),
  ('PH-LAN-BALOI', 'PH-LAN', 'Baloi'),
  ('PH-LAN-BAROY', 'PH-LAN', 'Baroy'),
  ('PH-LAN-ILIGAN-CITY', 'PH-LAN', 'Iligan City'),
  ('PH-LAN-KAPATAGAN', 'PH-LAN', 'Kapatagan'),
  ('PH-LAN-KAUSWAGAN', 'PH-LAN', 'Kauswagan'),
  ('PH-LAN-KOLAMBUGAN', 'PH-LAN', 'Kolambugan'),
  ('PH-LAN-LALA', 'PH-LAN', 'Lala'),
  ('PH-LAN-LINAMON', 'PH-LAN', 'Linamon'),
  ('PH-LAN-MAGSAYSAY', 'PH-LAN', 'Magsaysay'),
  ('PH-LAN-MAIGO', 'PH-LAN', 'Maigo'),
  ('PH-LAN-MATUNGAO', 'PH-LAN', 'Matungao'),
  ('PH-LAN-MUNAI', 'PH-LAN', 'Munai'),
  ('PH-LAN-NUNUNGAN', 'PH-LAN', 'Nunungan'),
  ('PH-LAN-PANTAO-RAGAT', 'PH-LAN', 'Pantao Ragat'),
  ('PH-LAN-PANTAR', 'PH-LAN', 'Pantar'),
  ('PH-LAN-POONA-PIAGAPO', 'PH-LAN', 'Poona Piagapo'),
  ('PH-LAN-SALVADOR', 'PH-LAN', 'Salvador'),
  ('PH-LAN-SAPAD', 'PH-LAN', 'Sapad'),
  ('PH-LAN-SULTAN-NAGA-DIMAPORO-KAROMATAN', 'PH-LAN', 'Sultan Naga Dimaporo (Karomatan)'),
  ('PH-LAN-TAGOLOAN', 'PH-LAN', 'Tagoloan'),
  ('PH-LAN-TANGCAL', 'PH-LAN', 'Tangcal'),
  ('PH-LAN-TUBOD', 'PH-LAN', 'Tubod'),
  ('PH-LAS-BACOLOD-KALAWI-BACOLOD-GRANDE', 'PH-LAS', 'Bacolod-Kalawi (Bacolod Grande)'),
  ('PH-LAS-BALABAGAN', 'PH-LAS', 'Balabagan'),
  ('PH-LAS-BALINDONG-WATU', 'PH-LAS', 'Balindong (Watu)'),
  ('PH-LAS-BAYANG', 'PH-LAS', 'Bayang'),
  ('PH-LAS-BINIDAYAN', 'PH-LAS', 'Binidayan'),
  ('PH-LAS-BUADIPOSO-BUNTONG', 'PH-LAS', 'Buadiposo-Buntong'),
  ('PH-LAS-BUBONG', 'PH-LAS', 'Bubong'),
  ('PH-LAS-BUMBARAN', 'PH-LAS', 'Bumbaran'),
  ('PH-LAS-BUTIG', 'PH-LAS', 'Butig'),
  ('PH-LAS-CALANOGAS', 'PH-LAS', 'Calanogas'),
  ('PH-LAS-DITSAAN-RAMAIN', 'PH-LAS', 'Ditsaan-Ramain'),
  ('PH-LAS-GANASSI', 'PH-LAS', 'Ganassi'),
  ('PH-LAS-KAPAI', 'PH-LAS', 'Kapai'),
  ('PH-LAS-KAPATAGAN', 'PH-LAS', 'Kapatagan'),
  ('PH-LAS-LUMBA-BAYABAO-MAGUING', 'PH-LAS', 'Lumba-Bayabao (Maguing)'),
  ('PH-LAS-LUMBACA-UNAYAN', 'PH-LAS', 'Lumbaca-Unayan'),
  ('PH-LAS-LUMBATAN', 'PH-LAS', 'Lumbatan'),
  ('PH-LAS-LUMBAYANAGUE', 'PH-LAS', 'Lumbayanague'),
  ('PH-LAS-MADALUM', 'PH-LAS', 'Madalum'),
  ('PH-LAS-MADAMBA', 'PH-LAS', 'Madamba'),
  ('PH-LAS-MAGUING', 'PH-LAS', 'Maguing'),
  ('PH-LAS-MALABANG', 'PH-LAS', 'Malabang'),
  ('PH-LAS-MARANTAO', 'PH-LAS', 'Marantao'),
  ('PH-LAS-MARAWI-CITY', 'PH-LAS', 'Marawi City'),
  ('PH-LAS-MAROGONG', 'PH-LAS', 'Marogong'),
  ('PH-LAS-MASIU', 'PH-LAS', 'Masiu'),
  ('PH-LAS-MULONDO', 'PH-LAS', 'Mulondo'),
  ('PH-LAS-PAGAYAWAN-TATARIKAN', 'PH-LAS', 'Pagayawan (Tatarikan)'),
  ('PH-LAS-PIAGAPO', 'PH-LAS', 'Piagapo'),
  ('PH-LAS-PICONG-SULTAN-GUMANDER', 'PH-LAS', 'Picong (Sultan Gumander)'),
  ('PH-LAS-POONA-BAYABAO-GATA', 'PH-LAS', 'Poona Bayabao (Gata)'),
  ('PH-LAS-PUALAS', 'PH-LAS', 'Pualas'),
  ('PH-LAS-SAGUIARAN', 'PH-LAS', 'Saguiaran'),
  ('PH-LAS-SULTAN-DUMALONDONG', 'PH-LAS', 'Sultan Dumalondong'),
  ('PH-LAS-TAGOLOAN-II', 'PH-LAS', 'Tagoloan II'),
  ('PH-LAS-TAMPARAN', 'PH-LAS', 'Tamparan'),
  ('PH-LAS-TARAKA', 'PH-LAS', 'Taraka'),
  ('PH-LAS-TUBARAN', 'PH-LAS', 'Tubaran'),
  ('PH-LAS-TUGAYA', 'PH-LAS', 'Tugaya'),
  ('PH-LAS-WAO', 'PH-LAS', 'Wao'),
  ('PH-LEY-ABUYOG', 'PH-LEY', 'Abuyog'),
  ('PH-LEY-ALANGALANG', 'PH-LEY', 'Alangalang'),
  ('PH-LEY-ALBUERA', 'PH-LEY', 'Albuera'),
  ('PH-LEY-BABATNGON', 'PH-LEY', 'Babatngon'),
  ('PH-LEY-BARUGO', 'PH-LEY', 'Barugo'),
  ('PH-LEY-BATO', 'PH-LEY', 'Bato'),
  ('PH-LEY-BAYBAY-CITY', 'PH-LEY', 'Baybay City'),
  ('PH-LEY-BURAUEN', 'PH-LEY', 'Burauen'),
  ('PH-LEY-CALUBIAN', 'PH-LEY', 'Calubian'),
  ('PH-LEY-CAPOOCAN', 'PH-LEY', 'Capoocan'),
  ('PH-LEY-CARIGARA', 'PH-LEY', 'Carigara'),
  ('PH-LEY-DAGAMI', 'PH-LEY', 'Dagami'),
  ('PH-LEY-DULAG', 'PH-LEY', 'Dulag'),
  ('PH-LEY-HILONGOS', 'PH-LEY', 'Hilongos'),
  ('PH-LEY-HINDANG', 'PH-LEY', 'Hindang'),
  ('PH-LEY-INOPACAN', 'PH-LEY', 'Inopacan'),
  ('PH-LEY-ISABEL', 'PH-LEY', 'Isabel'),
  ('PH-LEY-JARO', 'PH-LEY', 'Jaro'),
  ('PH-LEY-JAVIER-BUGHO', 'PH-LEY', 'Javier (Bugho)'),
  ('PH-LEY-JULITA', 'PH-LEY', 'Julita'),
  ('PH-LEY-KANANGA', 'PH-LEY', 'Kananga'),
  ('PH-LEY-LA-PAZ', 'PH-LEY', 'La Paz'),
  ('PH-LEY-LEYTE', 'PH-LEY', 'Leyte'),
  ('PH-LEY-MACARTHUR', 'PH-LEY', 'Macarthur'),
  ('PH-LEY-MAHAPLAG', 'PH-LEY', 'Mahaplag'),
  ('PH-LEY-MATAG-OB', 'PH-LEY', 'Matag-Ob'),
  ('PH-LEY-MATALOM', 'PH-LEY', 'Matalom'),
  ('PH-LEY-MAYORGA', 'PH-LEY', 'Mayorga'),
  ('PH-LEY-MERIDA', 'PH-LEY', 'Merida'),
  ('PH-LEY-ORMOC-CITY', 'PH-LEY', 'Ormoc City'),
  ('PH-LEY-PALO', 'PH-LEY', 'Palo'),
  ('PH-LEY-PALOMPON', 'PH-LEY', 'Palompon'),
  ('PH-LEY-PASTRANA', 'PH-LEY', 'Pastrana'),
  ('PH-LEY-SAN-ISIDRO', 'PH-LEY', 'San Isidro'),
  ('PH-LEY-SAN-MIGUEL', 'PH-LEY', 'San Miguel'),
  ('PH-LEY-SANTA-FE', 'PH-LEY', 'Santa Fe'),
  ('PH-LEY-TABANGO', 'PH-LEY', 'Tabango'),
  ('PH-LEY-TABONTABON', 'PH-LEY', 'Tabontabon'),
  ('PH-LEY-TACLOBAN-CITY', 'PH-LEY', 'Tacloban City'),
  ('PH-LEY-TANAUAN', 'PH-LEY', 'Tanauan'),
  ('PH-LEY-TOLOSA', 'PH-LEY', 'Tolosa'),
  ('PH-LEY-TUNGA', 'PH-LEY', 'Tunga'),
  ('PH-LEY-VILLABA', 'PH-LEY', 'Villaba'),
  ('PH-LUN-AGOO', 'PH-LUN', 'Agoo'),
  ('PH-LUN-ARINGAY', 'PH-LUN', 'Aringay'),
  ('PH-LUN-BACNOTAN', 'PH-LUN', 'Bacnotan'),
  ('PH-LUN-BAGULIN', 'PH-LUN', 'Bagulin'),
  ('PH-LUN-BALAOAN', 'PH-LUN', 'Balaoan'),
  ('PH-LUN-BANGAR', 'PH-LUN', 'Bangar'),
  ('PH-LUN-BAUANG', 'PH-LUN', 'Bauang'),
  ('PH-LUN-BURGOS', 'PH-LUN', 'Burgos'),
  ('PH-LUN-CABA', 'PH-LUN', 'Caba'),
  ('PH-LUN-LUNA', 'PH-LUN', 'Luna'),
  ('PH-LUN-NAGUILIAN', 'PH-LUN', 'Naguilian'),
  ('PH-LUN-PUGO', 'PH-LUN', 'Pugo'),
  ('PH-LUN-ROSARIO', 'PH-LUN', 'Rosario'),
  ('PH-LUN-SAN-FERNANDO-CITY', 'PH-LUN', 'San Fernando City'),
  ('PH-LUN-SAN-GABRIEL', 'PH-LUN', 'San Gabriel'),
  ('PH-LUN-SAN-JUAN', 'PH-LUN', 'San Juan'),
  ('PH-LUN-SANTO-TOMAS', 'PH-LUN', 'Santo Tomas'),
  ('PH-LUN-SANTOL', 'PH-LUN', 'Santol'),
  ('PH-LUN-SUDIPEN', 'PH-LUN', 'Sudipen'),
  ('PH-LUN-TUBAO', 'PH-LUN', 'Tubao'),
  ('PH-MAD-BOAC', 'PH-MAD', 'Boac'),
  ('PH-MAD-BUENAVISTA', 'PH-MAD', 'Buenavista'),
  ('PH-MAD-GASAN', 'PH-MAD', 'Gasan'),
  ('PH-MAD-MOGPOG', 'PH-MAD', 'Mogpog'),
  ('PH-MAD-SANTA-CRUZ', 'PH-MAD', 'Santa Cruz'),
  ('PH-MAD-TORRIJOS', 'PH-MAD', 'Torrijos'),
  ('PH-MAS-AROROY', 'PH-MAS', 'Aroroy'),
  ('PH-MAS-BALENO', 'PH-MAS', 'Baleno'),
  ('PH-MAS-BALUD', 'PH-MAS', 'Balud'),
  ('PH-MAS-BATUAN', 'PH-MAS', 'Batuan'),
  ('PH-MAS-CATAINGAN', 'PH-MAS', 'Cataingan'),
  ('PH-MAS-CAWAYAN', 'PH-MAS', 'Cawayan'),
  ('PH-MAS-CLAVERIA', 'PH-MAS', 'Claveria'),
  ('PH-MAS-DIMASALANG', 'PH-MAS', 'Dimasalang'),
  ('PH-MAS-ESPERANZA', 'PH-MAS', 'Esperanza'),
  ('PH-MAS-MANDAON', 'PH-MAS', 'Mandaon'),
  ('PH-MAS-MASBATE-CITY', 'PH-MAS', 'Masbate City'),
  ('PH-MAS-MILAGROS', 'PH-MAS', 'Milagros'),
  ('PH-MAS-MOBO', 'PH-MAS', 'Mobo'),
  ('PH-MAS-MONREAL', 'PH-MAS', 'Monreal'),
  ('PH-MAS-PALANAS', 'PH-MAS', 'Palanas'),
  ('PH-MAS-PIO-V-CORPUZ-LIMBUHAN', 'PH-MAS', 'Pio V. Corpuz (Limbuhan)'),
  ('PH-MAS-PLACER', 'PH-MAS', 'Placer'),
  ('PH-MAS-SAN-FERNANDO', 'PH-MAS', 'San Fernando'),
  ('PH-MAS-SAN-JACINTO', 'PH-MAS', 'San Jacinto'),
  ('PH-MAS-SAN-PASCUAL', 'PH-MAS', 'San Pascual'),
  ('PH-MAS-USON', 'PH-MAS', 'Uson'),
  ('PH-MDC-ABRA-DE-ILOG', 'PH-MDC', 'Abra De Ilog'),
  ('PH-MDC-CALINTAAN', 'PH-MDC', 'Calintaan'),
  ('PH-MDC-LOOC', 'PH-MDC', 'Looc'),
  ('PH-MDC-LUBANG', 'PH-MDC', 'Lubang'),
  ('PH-MDC-MAGSAYSAY', 'PH-MDC', 'Magsaysay'),
  ('PH-MDC-MAMBURAO', 'PH-MDC', 'Mamburao'),
  ('PH-MDC-PALUAN', 'PH-MDC', 'Paluan'),
  ('PH-MDC-RIZAL', 'PH-MDC', 'Rizal'),
  ('PH-MDC-SABLAYAN', 'PH-MDC', 'Sablayan'),
  ('PH-MDC-SAN-JOSE', 'PH-MDC', 'San Jose'),
  ('PH-MDC-SANTA-CRUZ', 'PH-MDC', 'Santa Cruz'),
  ('PH-MDR-BACO', 'PH-MDR', 'Baco'),
  ('PH-MDR-BANSUD', 'PH-MDR', 'Bansud'),
  ('PH-MDR-BONGABONG', 'PH-MDR', 'Bongabong'),
  ('PH-MDR-BULALACAO-SAN-PEDRO', 'PH-MDR', 'Bulalacao (San Pedro)'),
  ('PH-MDR-CALAPAN-CITY', 'PH-MDR', 'Calapan City'),
  ('PH-MDR-GLORIA', 'PH-MDR', 'Gloria'),
  ('PH-MDR-MANSALAY', 'PH-MDR', 'Mansalay'),
  ('PH-MDR-NAUJAN', 'PH-MDR', 'Naujan'),
  ('PH-MDR-PINAMALAYAN', 'PH-MDR', 'Pinamalayan'),
  ('PH-MDR-POLA', 'PH-MDR', 'Pola'),
  ('PH-MDR-PUERTO-GALERA', 'PH-MDR', 'Puerto Galera'),
  ('PH-MDR-ROXAS', 'PH-MDR', 'Roxas'),
  ('PH-MDR-SAN-TEODORO', 'PH-MDR', 'San Teodoro'),
  ('PH-MDR-SOCORRO', 'PH-MDR', 'Socorro'),
  ('PH-MDR-VICTORIA', 'PH-MDR', 'Victoria'),
  ('PH-MGN-BARIRA', 'PH-MGN', 'Barira'),
  ('PH-MGN-BULDON', 'PH-MGN', 'Buldon'),
  ('PH-MGN-DATU-BLAH-T-SINSUAT', 'PH-MGN', 'Datu Blah T. Sinsuat'),
  ('PH-MGN-DATU-ODIN-SINSUAT-DINAIG', 'PH-MGN', 'Datu Odin Sinsuat (Dinaig)'),
  ('PH-MGN-KABUNTALAN-TUMBAO', 'PH-MGN', 'Kabuntalan (Tumbao)'),
  ('PH-MGN-MATANOG', 'PH-MGN', 'Matanog'),
  ('PH-MGN-NORTHERN-KABUNTALAN', 'PH-MGN', 'Northern Kabuntalan'),
  ('PH-MGN-PARANG', 'PH-MGN', 'Parang'),
  ('PH-MGN-SULTAN-KUDARAT-NULING', 'PH-MGN', 'Sultan Kudarat (Nuling)'),
  ('PH-MGN-SULTAN-MASTURA', 'PH-MGN', 'Sultan Mastura'),
  ('PH-MGN-SULTAN-SUMAGKA-TALITAY', 'PH-MGN', 'Sultan Sumagka (Talitay)'),
  ('PH-MGN-UPI', 'PH-MGN', 'Upi'),
  ('PH-MGS-AMPATUAN', 'PH-MGS', 'Ampatuan'),
  ('PH-MGS-BULUAN', 'PH-MGS', 'Buluan'),
  ('PH-MGS-DATU-ABDULLAH-SANGKI', 'PH-MGS', 'Datu Abdullah Sangki'),
  ('PH-MGS-DATU-ANGGAL-MIDTIMBANG', 'PH-MGS', 'Datu Anggal Midtimbang'),
  ('PH-MGS-DATU-HOFFER-AMPATUAN', 'PH-MGS', 'Datu Hoffer Ampatuan'),
  ('PH-MGS-DATU-MONTAWAL-PAGAGAWAN', 'PH-MGS', 'Datu Montawal (Pagagawan)'),
  ('PH-MGS-DATU-PAGLAS', 'PH-MGS', 'Datu Paglas'),
  ('PH-MGS-DATU-PIANG', 'PH-MGS', 'Datu Piang'),
  ('PH-MGS-DATU-SALIBO', 'PH-MGS', 'Datu Salibo'),
  ('PH-MGS-DATU-SAUDI-AMPATUAN', 'PH-MGS', 'Datu Saudi-Ampatuan'),
  ('PH-MGS-DATU-UNSAY', 'PH-MGS', 'Datu Unsay'),
  ('PH-MGS-GENERAL-SALIPADA-K-PENDATUN', 'PH-MGS', 'General Salipada K. Pendatun'),
  ('PH-MGS-GUINDULUNGAN', 'PH-MGS', 'Guindulungan'),
  ('PH-MGS-MAMASAPANO', 'PH-MGS', 'Mamasapano'),
  ('PH-MGS-MANGUDADATU', 'PH-MGS', 'Mangudadatu'),
  ('PH-MGS-PAGALUNGAN', 'PH-MGS', 'Pagalungan'),
  ('PH-MGS-PAGLAT', 'PH-MGS', 'Paglat'),
  ('PH-MGS-PANDAG', 'PH-MGS', 'Pandag'),
  ('PH-MGS-RAJAH-BUAYAN', 'PH-MGS', 'Rajah Buayan'),
  ('PH-MGS-SHARIFF-SAYDONA-MUSTAPHA', 'PH-MGS', 'Shariff Saydona Mustapha'),
  ('PH-MGS-SOUTH-UPI', 'PH-MGS', 'South Upi'),
  ('PH-MGS-SULTAN-SA-BARONGIS-LAMBAYONG', 'PH-MGS', 'Sultan Sa Barongis (Lambayong)'),
  ('PH-MGS-TALAYAN', 'PH-MGS', 'Talayan'),
  ('PH-MOU-BARLIG', 'PH-MOU', 'Barlig'),
  ('PH-MOU-BAUKO', 'PH-MOU', 'Bauko'),
  ('PH-MOU-BESAO', 'PH-MOU', 'Besao'),
  ('PH-MOU-BONTOC', 'PH-MOU', 'Bontoc'),
  ('PH-MOU-NATONIN', 'PH-MOU', 'Natonin'),
  ('PH-MOU-PARACELIS', 'PH-MOU', 'Paracelis'),
  ('PH-MOU-SABANGAN', 'PH-MOU', 'Sabangan'),
  ('PH-MOU-SADANGA', 'PH-MOU', 'Sadanga'),
  ('PH-MOU-SAGADA', 'PH-MOU', 'Sagada'),
  ('PH-MOU-TADIAN', 'PH-MOU', 'Tadian'),
  ('PH-MSC-ALORAN', 'PH-MSC', 'Aloran'),
  ('PH-MSC-BALIANGAO', 'PH-MSC', 'Baliangao'),
  ('PH-MSC-BONIFACIO', 'PH-MSC', 'Bonifacio'),
  ('PH-MSC-CALAMBA', 'PH-MSC', 'Calamba'),
  ('PH-MSC-CLARIN', 'PH-MSC', 'Clarin'),
  ('PH-MSC-CONCEPCION', 'PH-MSC', 'Concepcion'),
  ('PH-MSC-DON-VICTORIANO-CHIONGBIAN-DON-MARIANO-MARCOS', 'PH-MSC', 'Don Victoriano Chiongbian  (Don Mariano Marcos)'),
  ('PH-MSC-JIMENEZ', 'PH-MSC', 'Jimenez'),
  ('PH-MSC-LOPEZ-JAENA', 'PH-MSC', 'Lopez Jaena'),
  ('PH-MSC-OROQUIETA-CITY', 'PH-MSC', 'Oroquieta City'),
  ('PH-MSC-OZAMIS-CITY', 'PH-MSC', 'Ozamis City'),
  ('PH-MSC-PANAON', 'PH-MSC', 'Panaon'),
  ('PH-MSC-PLARIDEL', 'PH-MSC', 'Plaridel'),
  ('PH-MSC-SAPANG-DALAGA', 'PH-MSC', 'Sapang Dalaga'),
  ('PH-MSC-SINACABAN', 'PH-MSC', 'Sinacaban'),
  ('PH-MSC-TANGUB-CITY', 'PH-MSC', 'Tangub City'),
  ('PH-MSC-TUDELA', 'PH-MSC', 'Tudela'),
  ('PH-MSR-ALUBIJID', 'PH-MSR', 'Alubijid'),
  ('PH-MSR-BALINGASAG', 'PH-MSR', 'Balingasag'),
  ('PH-MSR-BALINGOAN', 'PH-MSR', 'Balingoan'),
  ('PH-MSR-BINUANGAN', 'PH-MSR', 'Binuangan'),
  ('PH-MSR-CAGAYAN-DE-ORO-CITY', 'PH-MSR', 'Cagayan De Oro City'),
  ('PH-MSR-CLAVERIA', 'PH-MSR', 'Claveria'),
  ('PH-MSR-EL-SALVADOR-CITY', 'PH-MSR', 'El Salvador City'),
  ('PH-MSR-GINGOOG-CITY', 'PH-MSR', 'Gingoog City'),
  ('PH-MSR-GITAGUM', 'PH-MSR', 'Gitagum'),
  ('PH-MSR-INITAO', 'PH-MSR', 'Initao'),
  ('PH-MSR-JASAAN', 'PH-MSR', 'Jasaan'),
  ('PH-MSR-KINOGUITAN', 'PH-MSR', 'Kinoguitan'),
  ('PH-MSR-LAGONGLONG', 'PH-MSR', 'Lagonglong'),
  ('PH-MSR-LAGUINDINGAN', 'PH-MSR', 'Laguindingan'),
  ('PH-MSR-LIBERTAD', 'PH-MSR', 'Libertad'),
  ('PH-MSR-LUGAIT', 'PH-MSR', 'Lugait'),
  ('PH-MSR-MAGSAYSAY-LINUGOS', 'PH-MSR', 'Magsaysay (Linugos)'),
  ('PH-MSR-MANTICAO', 'PH-MSR', 'Manticao'),
  ('PH-MSR-MEDINA', 'PH-MSR', 'Medina'),
  ('PH-MSR-NAAWAN', 'PH-MSR', 'Naawan'),
  ('PH-MSR-OPOL', 'PH-MSR', 'Opol'),
  ('PH-MSR-SALAY', 'PH-MSR', 'Salay'),
  ('PH-MSR-SUGBONGCOGON', 'PH-MSR', 'Sugbongcogon'),
  ('PH-MSR-TAGOLOAN', 'PH-MSR', 'Tagoloan'),
  ('PH-MSR-TALISAYAN', 'PH-MSR', 'Talisayan'),
  ('PH-MSR-VILLANUEVA', 'PH-MSR', 'Villanueva'),
  ('PH-NCO-ALAMADA', 'PH-NCO', 'Alamada'),
  ('PH-NCO-ALEOSAN', 'PH-NCO', 'Aleosan'),
  ('PH-NCO-ANTIPAS', 'PH-NCO', 'Antipas'),
  ('PH-NCO-ARAKAN', 'PH-NCO', 'Arakan'),
  ('PH-NCO-BANISILAN', 'PH-NCO', 'Banisilan'),
  ('PH-NCO-CARMEN', 'PH-NCO', 'Carmen'),
  ('PH-NCO-KABACAN', 'PH-NCO', 'Kabacan'),
  ('PH-NCO-KIDAPAWAN-CITY', 'PH-NCO', 'Kidapawan City'),
  ('PH-NCO-LIBUNGAN', 'PH-NCO', 'Libungan'),
  ('PH-NCO-M-LANG', 'PH-NCO', 'M''Lang'),
  ('PH-NCO-MAGPET', 'PH-NCO', 'Magpet'),
  ('PH-NCO-MAKILALA', 'PH-NCO', 'Makilala'),
  ('PH-NCO-MATALAM', 'PH-NCO', 'Matalam'),
  ('PH-NCO-MIDSAYAP', 'PH-NCO', 'Midsayap'),
  ('PH-NCO-PIGKAWAYAN', 'PH-NCO', 'Pigkawayan'),
  ('PH-NCO-PIKIT', 'PH-NCO', 'Pikit'),
  ('PH-NCO-PRESIDENT-ROXAS', 'PH-NCO', 'President Roxas'),
  ('PH-NCO-TULUNAN', 'PH-NCO', 'Tulunan'),
  ('PH-NEC-BACOLOD-CITY', 'PH-NEC', 'Bacolod City'),
  ('PH-NEC-BAGO-CITY', 'PH-NEC', 'Bago City'),
  ('PH-NEC-BINALBAGAN', 'PH-NEC', 'Binalbagan'),
  ('PH-NEC-CADIZ-CITY', 'PH-NEC', 'Cadiz City'),
  ('PH-NEC-CALATRAVA', 'PH-NEC', 'Calatrava'),
  ('PH-NEC-CANDONI', 'PH-NEC', 'Candoni'),
  ('PH-NEC-CAUAYAN', 'PH-NEC', 'Cauayan'),
  ('PH-NEC-ENRIQUE-B-MAGALONA-SARAVIA', 'PH-NEC', 'Enrique B. Magalona (Saravia)'),
  ('PH-NEC-ESCALANTE-CITY', 'PH-NEC', 'Escalante City'),
  ('PH-NEC-HIMAMAYLAN-CITY', 'PH-NEC', 'Himamaylan City'),
  ('PH-NEC-HINIGARAN', 'PH-NEC', 'Hinigaran'),
  ('PH-NEC-HINOBA-AN-ASIA', 'PH-NEC', 'Hinoba-An (Asia)'),
  ('PH-NEC-ILOG', 'PH-NEC', 'Ilog'),
  ('PH-NEC-ISABELA', 'PH-NEC', 'Isabela'),
  ('PH-NEC-KABANKALAN-CITY', 'PH-NEC', 'Kabankalan City'),
  ('PH-NEC-LA-CARLOTA-CITY', 'PH-NEC', 'La Carlota City'),
  ('PH-NEC-LA-CASTELLANA', 'PH-NEC', 'La Castellana'),
  ('PH-NEC-MANAPLA', 'PH-NEC', 'Manapla'),
  ('PH-NEC-MOISES-PADILLA-MAGALLON', 'PH-NEC', 'Moises Padilla (Magallon)'),
  ('PH-NEC-MURCIA', 'PH-NEC', 'Murcia'),
  ('PH-NEC-PONTEVEDRA', 'PH-NEC', 'Pontevedra'),
  ('PH-NEC-PULUPANDAN', 'PH-NEC', 'Pulupandan'),
  ('PH-NEC-SAGAY-CITY', 'PH-NEC', 'Sagay City'),
  ('PH-NEC-SALVADOR-BENEDICTO', 'PH-NEC', 'Salvador Benedicto'),
  ('PH-NEC-SAN-CARLOS-CITY', 'PH-NEC', 'San Carlos City'),
  ('PH-NEC-SAN-ENRIQUE', 'PH-NEC', 'San Enrique'),
  ('PH-NEC-SILAY-CITY', 'PH-NEC', 'Silay City'),
  ('PH-NEC-SIPALAY-CITY', 'PH-NEC', 'Sipalay City'),
  ('PH-NEC-TALISAY-CITY', 'PH-NEC', 'Talisay City'),
  ('PH-NEC-TOBOSO', 'PH-NEC', 'Toboso'),
  ('PH-NEC-VALLADOLID', 'PH-NEC', 'Valladolid'),
  ('PH-NEC-VICTORIAS-CITY', 'PH-NEC', 'Victorias City'),
  ('PH-NER-AMLAN-AYUQUITAN', 'PH-NER', 'Amlan (Ayuquitan)'),
  ('PH-NER-AYUNGON', 'PH-NER', 'Ayungon'),
  ('PH-NER-BACONG', 'PH-NER', 'Bacong'),
  ('PH-NER-BAIS-CITY', 'PH-NER', 'Bais City'),
  ('PH-NER-BASAY', 'PH-NER', 'Basay'),
  ('PH-NER-BAYAWAN-TULONG-CITY', 'PH-NER', 'Bayawan (Tulong) City'),
  ('PH-NER-BINDOY-PAYABON', 'PH-NER', 'Bindoy (Payabon)'),
  ('PH-NER-CANLAON-CITY', 'PH-NER', 'Canlaon City'),
  ('PH-NER-DAUIN', 'PH-NER', 'Dauin'),
  ('PH-NER-DUMAGUETE-CITY', 'PH-NER', 'Dumaguete City'),
  ('PH-NER-GUIHULNGAN-CITY', 'PH-NER', 'Guihulngan City'),
  ('PH-NER-JIMALALUD', 'PH-NER', 'Jimalalud'),
  ('PH-NER-LA-LIBERTAD', 'PH-NER', 'La Libertad'),
  ('PH-NER-MABINAY', 'PH-NER', 'Mabinay'),
  ('PH-NER-MANJUYOD', 'PH-NER', 'Manjuyod'),
  ('PH-NER-PAMPLONA', 'PH-NER', 'Pamplona'),
  ('PH-NER-SAN-JOSE', 'PH-NER', 'San Jose'),
  ('PH-NER-SANTA-CATALINA', 'PH-NER', 'Santa Catalina'),
  ('PH-NER-SIATON', 'PH-NER', 'Siaton'),
  ('PH-NER-SIBULAN', 'PH-NER', 'Sibulan'),
  ('PH-NER-TANJAY-CITY', 'PH-NER', 'Tanjay City'),
  ('PH-NER-TAYASAN', 'PH-NER', 'Tayasan'),
  ('PH-NER-VALENCIA-LUZURRIAGA', 'PH-NER', 'Valencia (Luzurriaga)'),
  ('PH-NER-VALLEHERMOSO', 'PH-NER', 'Vallehermoso'),
  ('PH-NER-ZAMBOANGUITA', 'PH-NER', 'Zamboanguita'),
  ('PH-NSA-ALLEN', 'PH-NSA', 'Allen'),
  ('PH-NSA-BIRI', 'PH-NSA', 'Biri'),
  ('PH-NSA-BOBON', 'PH-NSA', 'Bobon'),
  ('PH-NSA-CAPUL', 'PH-NSA', 'Capul'),
  ('PH-NSA-CATARMAN', 'PH-NSA', 'Catarman'),
  ('PH-NSA-CATUBIG', 'PH-NSA', 'Catubig'),
  ('PH-NSA-GAMAY', 'PH-NSA', 'Gamay'),
  ('PH-NSA-LAOANG', 'PH-NSA', 'Laoang'),
  ('PH-NSA-LAPINIG', 'PH-NSA', 'Lapinig'),
  ('PH-NSA-LAS-NAVAS', 'PH-NSA', 'Las Navas'),
  ('PH-NSA-LAVEZARES', 'PH-NSA', 'Lavezares'),
  ('PH-NSA-LOPE-DE-VEGA', 'PH-NSA', 'Lope De Vega'),
  ('PH-NSA-MAPANAS', 'PH-NSA', 'Mapanas'),
  ('PH-NSA-MONDRAGON', 'PH-NSA', 'Mondragon'),
  ('PH-NSA-PALAPAG', 'PH-NSA', 'Palapag'),
  ('PH-NSA-PAMBUJAN', 'PH-NSA', 'Pambujan'),
  ('PH-NSA-ROSARIO', 'PH-NSA', 'Rosario'),
  ('PH-NSA-SAN-ANTONIO', 'PH-NSA', 'San Antonio'),
  ('PH-NSA-SAN-ISIDRO', 'PH-NSA', 'San Isidro'),
  ('PH-NSA-SAN-JOSE', 'PH-NSA', 'San Jose'),
  ('PH-NSA-SAN-ROQUE', 'PH-NSA', 'San Roque'),
  ('PH-NSA-SAN-VICENTE', 'PH-NSA', 'San Vicente'),
  ('PH-NSA-SILVINO-LOBOS', 'PH-NSA', 'Silvino Lobos'),
  ('PH-NSA-VICTORIA', 'PH-NSA', 'Victoria'),
  ('PH-NUE-ALIAGA', 'PH-NUE', 'Aliaga'),
  ('PH-NUE-BONGABON', 'PH-NUE', 'Bongabon'),
  ('PH-NUE-CABANATUAN-CITY', 'PH-NUE', 'Cabanatuan City'),
  ('PH-NUE-CABIAO', 'PH-NUE', 'Cabiao'),
  ('PH-NUE-CARRANGLAN', 'PH-NUE', 'Carranglan'),
  ('PH-NUE-CUYAPO', 'PH-NUE', 'Cuyapo'),
  ('PH-NUE-GABALDON-BITULOK-SABANI', 'PH-NUE', 'Gabaldon (Bitulok & Sabani)'),
  ('PH-NUE-GAPAN-CITY', 'PH-NUE', 'Gapan City'),
  ('PH-NUE-GENERAL-MAMERTO-NATIVIDAD', 'PH-NUE', 'General Mamerto Natividad'),
  ('PH-NUE-GENERAL-TINIO-PAPAYA', 'PH-NUE', 'General Tinio (Papaya)'),
  ('PH-NUE-GUIMBA', 'PH-NUE', 'Guimba'),
  ('PH-NUE-JAEN', 'PH-NUE', 'Jaen'),
  ('PH-NUE-LAUR', 'PH-NUE', 'Laur'),
  ('PH-NUE-LICAB', 'PH-NUE', 'Licab'),
  ('PH-NUE-LLANERA', 'PH-NUE', 'Llanera'),
  ('PH-NUE-LUPAO', 'PH-NUE', 'Lupao'),
  ('PH-NUE-NAMPICUAN', 'PH-NUE', 'Nampicuan'),
  ('PH-NUE-PALAYAN-CITY', 'PH-NUE', 'Palayan City'),
  ('PH-NUE-PANTABANGAN', 'PH-NUE', 'Pantabangan'),
  ('PH-NUE-PENARANDA', 'PH-NUE', 'Peñaranda'),
  ('PH-NUE-QUEZON', 'PH-NUE', 'Quezon'),
  ('PH-NUE-RIZAL', 'PH-NUE', 'Rizal'),
  ('PH-NUE-SAN-ANTONIO', 'PH-NUE', 'San Antonio'),
  ('PH-NUE-SAN-ISIDRO', 'PH-NUE', 'San Isidro'),
  ('PH-NUE-SAN-JOSE-CITY', 'PH-NUE', 'San Jose City'),
  ('PH-NUE-SAN-LEONARDO', 'PH-NUE', 'San Leonardo'),
  ('PH-NUE-SANTA-ROSA', 'PH-NUE', 'Santa Rosa'),
  ('PH-NUE-SANTO-DOMINGO', 'PH-NUE', 'Santo Domingo'),
  ('PH-NUE-SCIENCE-CITY-OF-MUNOZ', 'PH-NUE', 'Science City Of Muñoz'),
  ('PH-NUE-TALAVERA', 'PH-NUE', 'Talavera'),
  ('PH-NUE-TALUGTUG', 'PH-NUE', 'Talugtug'),
  ('PH-NUE-ZARAGOZA', 'PH-NUE', 'Zaragoza'),
  ('PH-NUV-ALFONSO-CASTANEDA', 'PH-NUV', 'Alfonso Castaneda'),
  ('PH-NUV-AMBAGUIO', 'PH-NUV', 'Ambaguio'),
  ('PH-NUV-ARITAO', 'PH-NUV', 'Aritao'),
  ('PH-NUV-BAGABAG', 'PH-NUV', 'Bagabag'),
  ('PH-NUV-BAMBANG', 'PH-NUV', 'Bambang'),
  ('PH-NUV-BAYOMBONG', 'PH-NUV', 'Bayombong'),
  ('PH-NUV-DIADI', 'PH-NUV', 'Diadi'),
  ('PH-NUV-DUPAX-DEL-NORTE', 'PH-NUV', 'Dupax Del Norte'),
  ('PH-NUV-DUPAX-DEL-SUR', 'PH-NUV', 'Dupax Del Sur'),
  ('PH-NUV-KASIBU', 'PH-NUV', 'Kasibu'),
  ('PH-NUV-KAYAPA', 'PH-NUV', 'Kayapa'),
  ('PH-NUV-QUEZON', 'PH-NUV', 'Quezon'),
  ('PH-NUV-SANTA-FE', 'PH-NUV', 'Santa Fe'),
  ('PH-NUV-SOLANO', 'PH-NUV', 'Solano'),
  ('PH-NUV-VILLAVERDE', 'PH-NUV', 'Villaverde'),
  ('PH-PAM-ANGELES-CITY', 'PH-PAM', 'Angeles City'),
  ('PH-PAM-APALIT', 'PH-PAM', 'Apalit'),
  ('PH-PAM-ARAYAT', 'PH-PAM', 'Arayat'),
  ('PH-PAM-BACOLOR', 'PH-PAM', 'Bacolor'),
  ('PH-PAM-CANDABA', 'PH-PAM', 'Candaba'),
  ('PH-PAM-FLORIDABLANCA', 'PH-PAM', 'Floridablanca'),
  ('PH-PAM-GUAGUA', 'PH-PAM', 'Guagua'),
  ('PH-PAM-LUBAO', 'PH-PAM', 'Lubao'),
  ('PH-PAM-MABALACAT-CITY', 'PH-PAM', 'Mabalacat City'),
  ('PH-PAM-MACABEBE', 'PH-PAM', 'Macabebe'),
  ('PH-PAM-MAGALANG', 'PH-PAM', 'Magalang'),
  ('PH-PAM-MASANTOL', 'PH-PAM', 'Masantol'),
  ('PH-PAM-MEXICO', 'PH-PAM', 'Mexico'),
  ('PH-PAM-MINALIN', 'PH-PAM', 'Minalin'),
  ('PH-PAM-PORAC', 'PH-PAM', 'Porac'),
  ('PH-PAM-SAN-FERNANDO-CITY', 'PH-PAM', 'San Fernando City'),
  ('PH-PAM-SAN-LUIS', 'PH-PAM', 'San Luis'),
  ('PH-PAM-SAN-SIMON', 'PH-PAM', 'San Simon'),
  ('PH-PAM-SANTA-ANA', 'PH-PAM', 'Santa Ana'),
  ('PH-PAM-SANTA-RITA', 'PH-PAM', 'Santa Rita'),
  ('PH-PAM-SANTO-TOMAS', 'PH-PAM', 'Santo Tomas'),
  ('PH-PAM-SASMUAN-SEXMOAN', 'PH-PAM', 'Sasmuan (Sexmoan)'),
  ('PH-PAN-AGNO', 'PH-PAN', 'Agno'),
  ('PH-PAN-AGUILAR', 'PH-PAN', 'Aguilar'),
  ('PH-PAN-ALAMINOS-CITY', 'PH-PAN', 'Alaminos City'),
  ('PH-PAN-ALCALA', 'PH-PAN', 'Alcala'),
  ('PH-PAN-ANDA', 'PH-PAN', 'Anda'),
  ('PH-PAN-ASINGAN', 'PH-PAN', 'Asingan'),
  ('PH-PAN-BALUNGAO', 'PH-PAN', 'Balungao'),
  ('PH-PAN-BANI', 'PH-PAN', 'Bani'),
  ('PH-PAN-BASISTA', 'PH-PAN', 'Basista'),
  ('PH-PAN-BAUTISTA', 'PH-PAN', 'Bautista'),
  ('PH-PAN-BAYAMBANG', 'PH-PAN', 'Bayambang'),
  ('PH-PAN-BINALONAN', 'PH-PAN', 'Binalonan'),
  ('PH-PAN-BINMALEY', 'PH-PAN', 'Binmaley'),
  ('PH-PAN-BOLINAO', 'PH-PAN', 'Bolinao'),
  ('PH-PAN-BUGALLON', 'PH-PAN', 'Bugallon'),
  ('PH-PAN-BURGOS', 'PH-PAN', 'Burgos'),
  ('PH-PAN-CALASIAO', 'PH-PAN', 'Calasiao'),
  ('PH-PAN-DAGUPAN-CITY', 'PH-PAN', 'Dagupan City'),
  ('PH-PAN-DASOL', 'PH-PAN', 'Dasol'),
  ('PH-PAN-INFANTA', 'PH-PAN', 'Infanta'),
  ('PH-PAN-LABRADOR', 'PH-PAN', 'Labrador'),
  ('PH-PAN-LAOAC', 'PH-PAN', 'Laoac'),
  ('PH-PAN-LINGAYEN', 'PH-PAN', 'Lingayen'),
  ('PH-PAN-MABINI', 'PH-PAN', 'Mabini'),
  ('PH-PAN-MALASIQUI', 'PH-PAN', 'Malasiqui'),
  ('PH-PAN-MANAOAG', 'PH-PAN', 'Manaoag'),
  ('PH-PAN-MANGALDAN', 'PH-PAN', 'Mangaldan'),
  ('PH-PAN-MANGATAREM', 'PH-PAN', 'Mangatarem'),
  ('PH-PAN-MAPANDAN', 'PH-PAN', 'Mapandan'),
  ('PH-PAN-NATIVIDAD', 'PH-PAN', 'Natividad'),
  ('PH-PAN-POZORRUBIO', 'PH-PAN', 'Pozorrubio'),
  ('PH-PAN-ROSALES', 'PH-PAN', 'Rosales'),
  ('PH-PAN-SAN-CARLOS-CITY', 'PH-PAN', 'San Carlos City'),
  ('PH-PAN-SAN-FABIAN', 'PH-PAN', 'San Fabian'),
  ('PH-PAN-SAN-JACINTO', 'PH-PAN', 'San Jacinto'),
  ('PH-PAN-SAN-MANUEL', 'PH-PAN', 'San Manuel'),
  ('PH-PAN-SAN-NICOLAS', 'PH-PAN', 'San Nicolas'),
  ('PH-PAN-SAN-QUINTIN', 'PH-PAN', 'San Quintin'),
  ('PH-PAN-SANTA-BARBARA', 'PH-PAN', 'Santa Barbara'),
  ('PH-PAN-SANTA-MARIA', 'PH-PAN', 'Santa Maria'),
  ('PH-PAN-SANTO-TOMAS', 'PH-PAN', 'Santo Tomas'),
  ('PH-PAN-SISON', 'PH-PAN', 'Sison'),
  ('PH-PAN-SUAL', 'PH-PAN', 'Sual'),
  ('PH-PAN-TAYUG', 'PH-PAN', 'Tayug'),
  ('PH-PAN-UMINGAN', 'PH-PAN', 'Umingan'),
  ('PH-PAN-URBIZTONDO', 'PH-PAN', 'Urbiztondo'),
  ('PH-PAN-URDANETA-CITY', 'PH-PAN', 'Urdaneta City'),
  ('PH-PAN-VILLASIS', 'PH-PAN', 'Villasis'),
  ('PH-PLW-ABORLAN', 'PH-PLW', 'Aborlan'),
  ('PH-PLW-AGUTAYA', 'PH-PLW', 'Agutaya'),
  ('PH-PLW-ARACELI', 'PH-PLW', 'Araceli'),
  ('PH-PLW-BALABAC', 'PH-PLW', 'Balabac'),
  ('PH-PLW-BATARAZA', 'PH-PLW', 'Bataraza'),
  ('PH-PLW-BROOKE-S-POINT', 'PH-PLW', 'Brooke''S Point'),
  ('PH-PLW-BUSUANGA', 'PH-PLW', 'Busuanga'),
  ('PH-PLW-CAGAYANCILLO', 'PH-PLW', 'Cagayancillo'),
  ('PH-PLW-CORON', 'PH-PLW', 'Coron'),
  ('PH-PLW-CULION', 'PH-PLW', 'Culion'),
  ('PH-PLW-CUYO', 'PH-PLW', 'Cuyo'),
  ('PH-PLW-DUMARAN', 'PH-PLW', 'Dumaran'),
  ('PH-PLW-EL-NIDO-BACUIT', 'PH-PLW', 'El Nido (Bacuit)'),
  ('PH-PLW-KALAYAAN', 'PH-PLW', 'Kalayaan'),
  ('PH-PLW-LINAPACAN', 'PH-PLW', 'Linapacan'),
  ('PH-PLW-MAGSAYSAY', 'PH-PLW', 'Magsaysay'),
  ('PH-PLW-NARRA', 'PH-PLW', 'Narra'),
  ('PH-PLW-PUERTO-PRINCESA-CITY', 'PH-PLW', 'Puerto Princesa City'),
  ('PH-PLW-QUEZON', 'PH-PLW', 'Quezon'),
  ('PH-PLW-RIZAL-MARCOS', 'PH-PLW', 'Rizal (Marcos)'),
  ('PH-PLW-ROXAS', 'PH-PLW', 'Roxas'),
  ('PH-PLW-SAN-VICENTE', 'PH-PLW', 'San Vicente'),
  ('PH-PLW-SOFRONIO-ESPANOLA', 'PH-PLW', 'Sofronio Española'),
  ('PH-PLW-TAYTAY', 'PH-PLW', 'Taytay'),
  ('PH-QUE-AGDANGAN', 'PH-QUE', 'Agdangan'),
  ('PH-QUE-ALABAT', 'PH-QUE', 'Alabat'),
  ('PH-QUE-ATIMONAN', 'PH-QUE', 'Atimonan'),
  ('PH-QUE-BUENAVISTA', 'PH-QUE', 'Buenavista'),
  ('PH-QUE-BURDEOS', 'PH-QUE', 'Burdeos'),
  ('PH-QUE-CALAUAG', 'PH-QUE', 'Calauag'),
  ('PH-QUE-CANDELARIA', 'PH-QUE', 'Candelaria'),
  ('PH-QUE-CATANAUAN', 'PH-QUE', 'Catanauan'),
  ('PH-QUE-DOLORES', 'PH-QUE', 'Dolores'),
  ('PH-QUE-GENERAL-LUNA', 'PH-QUE', 'General Luna'),
  ('PH-QUE-GENERAL-NAKAR', 'PH-QUE', 'General Nakar'),
  ('PH-QUE-GUINAYANGAN', 'PH-QUE', 'Guinayangan'),
  ('PH-QUE-GUMACA', 'PH-QUE', 'Gumaca'),
  ('PH-QUE-INFANTA', 'PH-QUE', 'Infanta'),
  ('PH-QUE-JOMALIG', 'PH-QUE', 'Jomalig'),
  ('PH-QUE-LOPEZ', 'PH-QUE', 'Lopez'),
  ('PH-QUE-LUCBAN', 'PH-QUE', 'Lucban'),
  ('PH-QUE-LUCENA-CITY', 'PH-QUE', 'Lucena City'),
  ('PH-QUE-MACALELON', 'PH-QUE', 'Macalelon'),
  ('PH-QUE-MAUBAN', 'PH-QUE', 'Mauban'),
  ('PH-QUE-MULANAY', 'PH-QUE', 'Mulanay'),
  ('PH-QUE-PADRE-BURGOS', 'PH-QUE', 'Padre Burgos'),
  ('PH-QUE-PAGBILAO', 'PH-QUE', 'Pagbilao'),
  ('PH-QUE-PANUKULAN', 'PH-QUE', 'Panukulan'),
  ('PH-QUE-PATNANUNGAN', 'PH-QUE', 'Patnanungan'),
  ('PH-QUE-PEREZ', 'PH-QUE', 'Perez'),
  ('PH-QUE-PITOGO', 'PH-QUE', 'Pitogo'),
  ('PH-QUE-PLARIDEL', 'PH-QUE', 'Plaridel'),
  ('PH-QUE-POLILLO', 'PH-QUE', 'Polillo'),
  ('PH-QUE-QUEZON', 'PH-QUE', 'Quezon'),
  ('PH-QUE-REAL', 'PH-QUE', 'Real'),
  ('PH-QUE-SAMPALOC', 'PH-QUE', 'Sampaloc'),
  ('PH-QUE-SAN-ANDRES', 'PH-QUE', 'San Andres'),
  ('PH-QUE-SAN-ANTONIO', 'PH-QUE', 'San Antonio'),
  ('PH-QUE-SAN-FRANCISCO-AURORA', 'PH-QUE', 'San Francisco (Aurora)'),
  ('PH-QUE-SAN-NARCISO', 'PH-QUE', 'San Narciso'),
  ('PH-QUE-SARIAYA', 'PH-QUE', 'Sariaya'),
  ('PH-QUE-TAGKAWAYAN', 'PH-QUE', 'Tagkawayan'),
  ('PH-QUE-TAYABAS-CITY', 'PH-QUE', 'Tayabas City'),
  ('PH-QUE-TIAONG', 'PH-QUE', 'Tiaong'),
  ('PH-QUE-UNISAN', 'PH-QUE', 'Unisan'),
  ('PH-QUI-AGLIPAY', 'PH-QUI', 'Aglipay'),
  ('PH-QUI-CABARROGUIS', 'PH-QUI', 'Cabarroguis'),
  ('PH-QUI-DIFFUN', 'PH-QUI', 'Diffun'),
  ('PH-QUI-MADDELA', 'PH-QUI', 'Maddela'),
  ('PH-QUI-NAGTIPUNAN', 'PH-QUI', 'Nagtipunan'),
  ('PH-QUI-SAGUDAY', 'PH-QUI', 'Saguday'),
  ('PH-RIZ-ANGONO', 'PH-RIZ', 'Angono'),
  ('PH-RIZ-ANTIPOLO-CITY', 'PH-RIZ', 'Antipolo City'),
  ('PH-RIZ-BARAS', 'PH-RIZ', 'Baras'),
  ('PH-RIZ-BINANGONAN', 'PH-RIZ', 'Binangonan'),
  ('PH-RIZ-CAINTA', 'PH-RIZ', 'Cainta'),
  ('PH-RIZ-CARDONA', 'PH-RIZ', 'Cardona'),
  ('PH-RIZ-JALA-JALA', 'PH-RIZ', 'Jala-Jala'),
  ('PH-RIZ-MORONG', 'PH-RIZ', 'Morong'),
  ('PH-RIZ-PILILLA', 'PH-RIZ', 'Pililla'),
  ('PH-RIZ-RODRIGUEZ-MONTALBAN', 'PH-RIZ', 'Rodriguez (Montalban)'),
  ('PH-RIZ-SAN-MATEO', 'PH-RIZ', 'San Mateo'),
  ('PH-RIZ-TANAY', 'PH-RIZ', 'Tanay'),
  ('PH-RIZ-TAYTAY', 'PH-RIZ', 'Taytay'),
  ('PH-RIZ-TERESA', 'PH-RIZ', 'Teresa'),
  ('PH-ROM-ALCANTARA', 'PH-ROM', 'Alcantara'),
  ('PH-ROM-BANTON', 'PH-ROM', 'Banton'),
  ('PH-ROM-CAJIDIOCAN', 'PH-ROM', 'Cajidiocan'),
  ('PH-ROM-CALATRAVA', 'PH-ROM', 'Calatrava'),
  ('PH-ROM-CONCEPCION', 'PH-ROM', 'Concepcion'),
  ('PH-ROM-CORCUERA', 'PH-ROM', 'Corcuera'),
  ('PH-ROM-FERROL', 'PH-ROM', 'Ferrol'),
  ('PH-ROM-LOOC', 'PH-ROM', 'Looc'),
  ('PH-ROM-MAGDIWANG', 'PH-ROM', 'Magdiwang'),
  ('PH-ROM-ODIONGAN', 'PH-ROM', 'Odiongan'),
  ('PH-ROM-ROMBLON', 'PH-ROM', 'Romblon'),
  ('PH-ROM-SAN-AGUSTIN', 'PH-ROM', 'San Agustin'),
  ('PH-ROM-SAN-ANDRES', 'PH-ROM', 'San Andres'),
  ('PH-ROM-SAN-FERNANDO', 'PH-ROM', 'San Fernando'),
  ('PH-ROM-SAN-JOSE', 'PH-ROM', 'San Jose'),
  ('PH-ROM-SANTA-FE', 'PH-ROM', 'Santa Fe'),
  ('PH-ROM-SANTA-MARIA-IMELDA', 'PH-ROM', 'Santa Maria (Imelda)'),
  ('PH-SAR-ALABEL', 'PH-SAR', 'Alabel'),
  ('PH-SAR-GLAN', 'PH-SAR', 'Glan'),
  ('PH-SAR-KIAMBA', 'PH-SAR', 'Kiamba'),
  ('PH-SAR-MAASIM', 'PH-SAR', 'Maasim'),
  ('PH-SAR-MAITUM', 'PH-SAR', 'Maitum'),
  ('PH-SAR-MALAPATAN', 'PH-SAR', 'Malapatan'),
  ('PH-SAR-MALUNGON', 'PH-SAR', 'Malungon'),
  ('PH-SCO-BANGA', 'PH-SCO', 'Banga'),
  ('PH-SCO-GENERAL-SANTOS-CITY-DADIANGAS', 'PH-SCO', 'General Santos City (Dadiangas)'),
  ('PH-SCO-KORONADAL-CITY', 'PH-SCO', 'Koronadal City'),
  ('PH-SCO-LAKE-SEBU', 'PH-SCO', 'Lake Sebu'),
  ('PH-SCO-NORALA', 'PH-SCO', 'Norala'),
  ('PH-SCO-POLOMOLOK', 'PH-SCO', 'Polomolok'),
  ('PH-SCO-SANTO-NINO', 'PH-SCO', 'Santo Niño'),
  ('PH-SCO-SURALLAH', 'PH-SCO', 'Surallah'),
  ('PH-SCO-T-BOLI', 'PH-SCO', 'T''Boli'),
  ('PH-SCO-TAMPAKAN', 'PH-SCO', 'Tampakan'),
  ('PH-SCO-TANTANGAN', 'PH-SCO', 'Tantangan'),
  ('PH-SCO-TUPI', 'PH-SCO', 'Tupi'),
  ('PH-SIG-ENRIQUE-VILLANUEVA', 'PH-SIG', 'Enrique Villanueva'),
  ('PH-SIG-LARENA', 'PH-SIG', 'Larena'),
  ('PH-SIG-LAZI', 'PH-SIG', 'Lazi'),
  ('PH-SIG-MARIA', 'PH-SIG', 'Maria'),
  ('PH-SIG-SAN-JUAN', 'PH-SIG', 'San Juan'),
  ('PH-SIG-SIQUIJOR', 'PH-SIG', 'Siquijor'),
  ('PH-SLE-ANAHAWAN', 'PH-SLE', 'Anahawan'),
  ('PH-SLE-BONTOC', 'PH-SLE', 'Bontoc'),
  ('PH-SLE-HINUNANGAN', 'PH-SLE', 'Hinunangan'),
  ('PH-SLE-HINUNDAYAN', 'PH-SLE', 'Hinundayan'),
  ('PH-SLE-LIBAGON', 'PH-SLE', 'Libagon'),
  ('PH-SLE-LILOAN', 'PH-SLE', 'Liloan'),
  ('PH-SLE-LIMASAWA', 'PH-SLE', 'Limasawa'),
  ('PH-SLE-MAASIN-CITY', 'PH-SLE', 'Maasin City'),
  ('PH-SLE-MACROHON', 'PH-SLE', 'Macrohon'),
  ('PH-SLE-MALITBOG', 'PH-SLE', 'Malitbog'),
  ('PH-SLE-PADRE-BURGOS', 'PH-SLE', 'Padre Burgos'),
  ('PH-SLE-PINTUYAN', 'PH-SLE', 'Pintuyan'),
  ('PH-SLE-SAINT-BERNARD', 'PH-SLE', 'Saint Bernard'),
  ('PH-SLE-SAN-FRANCISCO', 'PH-SLE', 'San Francisco'),
  ('PH-SLE-SAN-JUAN-CABALIAN', 'PH-SLE', 'San Juan (Cabalian)'),
  ('PH-SLE-SAN-RICARDO', 'PH-SLE', 'San Ricardo'),
  ('PH-SLE-SILAGO', 'PH-SLE', 'Silago'),
  ('PH-SLE-SOGOD', 'PH-SLE', 'Sogod'),
  ('PH-SLE-TOMAS-OPPUS', 'PH-SLE', 'Tomas Oppus'),
  ('PH-SLU-HADJI-PANGLIMA-TAHIL-MARUNGGAS', 'PH-SLU', 'Hadji Panglima Tahil (Marunggas)'),
  ('PH-SLU-INDANAN', 'PH-SLU', 'Indanan'),
  ('PH-SLU-JOLO', 'PH-SLU', 'Jolo'),
  ('PH-SLU-KALINGALAN-CALUANG', 'PH-SLU', 'Kalingalan Caluang'),
  ('PH-SLU-LUGUS', 'PH-SLU', 'Lugus'),
  ('PH-SLU-LUUK', 'PH-SLU', 'Luuk'),
  ('PH-SLU-MAIMBUNG', 'PH-SLU', 'Maimbung'),
  ('PH-SLU-OLD-PANAMAO', 'PH-SLU', 'Old Panamao'),
  ('PH-SLU-OMAR', 'PH-SLU', 'Omar'),
  ('PH-SLU-PANDAMI', 'PH-SLU', 'Pandami'),
  ('PH-SLU-PANGLIMA-ESTINO-NEW-PANAMAO', 'PH-SLU', 'Panglima Estino (New Panamao)'),
  ('PH-SLU-PANGUTARAN', 'PH-SLU', 'Pangutaran'),
  ('PH-SLU-PARANG', 'PH-SLU', 'Parang'),
  ('PH-SLU-PATA', 'PH-SLU', 'Pata'),
  ('PH-SLU-PATIKUL', 'PH-SLU', 'Patikul'),
  ('PH-SLU-SIASI', 'PH-SLU', 'Siasi'),
  ('PH-SLU-TALIPAO', 'PH-SLU', 'Talipao'),
  ('PH-SLU-TAPUL', 'PH-SLU', 'Tapul'),
  ('PH-SLU-TONGKIL', 'PH-SLU', 'Tongkil'),
  ('PH-SOR-BARCELONA', 'PH-SOR', 'Barcelona'),
  ('PH-SOR-BULAN', 'PH-SOR', 'Bulan'),
  ('PH-SOR-BULUSAN', 'PH-SOR', 'Bulusan'),
  ('PH-SOR-CASIGURAN', 'PH-SOR', 'Casiguran'),
  ('PH-SOR-CASTILLA', 'PH-SOR', 'Castilla'),
  ('PH-SOR-DONSOL', 'PH-SOR', 'Donsol'),
  ('PH-SOR-GUBAT', 'PH-SOR', 'Gubat'),
  ('PH-SOR-IROSIN', 'PH-SOR', 'Irosin'),
  ('PH-SOR-JUBAN', 'PH-SOR', 'Juban'),
  ('PH-SOR-MAGALLANES', 'PH-SOR', 'Magallanes'),
  ('PH-SOR-MATNOG', 'PH-SOR', 'Matnog'),
  ('PH-SOR-PILAR', 'PH-SOR', 'Pilar'),
  ('PH-SOR-PRIETO-DIAZ', 'PH-SOR', 'Prieto Diaz'),
  ('PH-SOR-SANTA-MAGDALENA', 'PH-SOR', 'Santa Magdalena'),
  ('PH-SOR-SORSOGON-CITY', 'PH-SOR', 'Sorsogon City'),
  ('PH-SUK-BAGUMBAYAN', 'PH-SUK', 'Bagumbayan'),
  ('PH-SUK-COLUMBIO', 'PH-SUK', 'Columbio'),
  ('PH-SUK-ESPERANZA', 'PH-SUK', 'Esperanza'),
  ('PH-SUK-ISULAN', 'PH-SUK', 'Isulan'),
  ('PH-SUK-KALAMANSIG', 'PH-SUK', 'Kalamansig'),
  ('PH-SUK-LAMBAYONG-MARIANO-MARCOS', 'PH-SUK', 'Lambayong (Mariano Marcos)'),
  ('PH-SUK-LEBAK', 'PH-SUK', 'Lebak'),
  ('PH-SUK-LUTAYAN', 'PH-SUK', 'Lutayan'),
  ('PH-SUK-PALIMBANG', 'PH-SUK', 'Palimbang'),
  ('PH-SUK-PRESIDENT-QUIRINO', 'PH-SUK', 'President Quirino'),
  ('PH-SUK-SEN-NINOY-AQUINO', 'PH-SUK', 'Sen. Ninoy Aquino'),
  ('PH-SUK-TACURONG-CITY', 'PH-SUK', 'Tacurong City'),
  ('PH-SUN-ALEGRIA', 'PH-SUN', 'Alegria'),
  ('PH-SUN-BACUAG', 'PH-SUN', 'Bacuag'),
  ('PH-SUN-BURGOS', 'PH-SUN', 'Burgos'),
  ('PH-SUN-CLAVER', 'PH-SUN', 'Claver'),
  ('PH-SUN-DAPA', 'PH-SUN', 'Dapa'),
  ('PH-SUN-DEL-CARMEN', 'PH-SUN', 'Del Carmen'),
  ('PH-SUN-GENERAL-LUNA', 'PH-SUN', 'General Luna'),
  ('PH-SUN-GIGAQUIT', 'PH-SUN', 'Gigaquit'),
  ('PH-SUN-MAINIT', 'PH-SUN', 'Mainit'),
  ('PH-SUN-MALIMONO', 'PH-SUN', 'Malimono'),
  ('PH-SUN-PILAR', 'PH-SUN', 'Pilar'),
  ('PH-SUN-PLACER', 'PH-SUN', 'Placer'),
  ('PH-SUN-SAN-BENITO', 'PH-SUN', 'San Benito'),
  ('PH-SUN-SAN-FRANCISCO-ANAO-AON', 'PH-SUN', 'San Francisco (Anao-Aon)'),
  ('PH-SUN-SAN-ISIDRO', 'PH-SUN', 'San Isidro'),
  ('PH-SUN-SANTA-MONICA-SAPAO', 'PH-SUN', 'Santa Monica (Sapao)'),
  ('PH-SUN-SISON', 'PH-SUN', 'Sison'),
  ('PH-SUN-SOCORRO', 'PH-SUN', 'Socorro'),
  ('PH-SUN-SURIGAO-CITY', 'PH-SUN', 'Surigao City'),
  ('PH-SUN-TAGANA-AN', 'PH-SUN', 'Tagana-An'),
  ('PH-SUN-TUBOD', 'PH-SUN', 'Tubod'),
  ('PH-SUR-BAROBO', 'PH-SUR', 'Barobo'),
  ('PH-SUR-BAYABAS', 'PH-SUR', 'Bayabas'),
  ('PH-SUR-BISLIG-CITY', 'PH-SUR', 'Bislig City'),
  ('PH-SUR-CAGWAIT', 'PH-SUR', 'Cagwait'),
  ('PH-SUR-CANTILAN', 'PH-SUR', 'Cantilan'),
  ('PH-SUR-CARMEN', 'PH-SUR', 'Carmen'),
  ('PH-SUR-CARRASCAL', 'PH-SUR', 'Carrascal'),
  ('PH-SUR-CORTES', 'PH-SUR', 'Cortes'),
  ('PH-SUR-HINATUAN', 'PH-SUR', 'Hinatuan'),
  ('PH-SUR-LANUZA', 'PH-SUR', 'Lanuza'),
  ('PH-SUR-LIANGA', 'PH-SUR', 'Lianga'),
  ('PH-SUR-LINGIG', 'PH-SUR', 'Lingig'),
  ('PH-SUR-MADRID', 'PH-SUR', 'Madrid'),
  ('PH-SUR-MARIHATAG', 'PH-SUR', 'Marihatag'),
  ('PH-SUR-SAN-AGUSTIN', 'PH-SUR', 'San Agustin'),
  ('PH-SUR-SAN-MIGUEL', 'PH-SUR', 'San Miguel'),
  ('PH-SUR-TAGBINA', 'PH-SUR', 'Tagbina'),
  ('PH-SUR-TAGO', 'PH-SUR', 'Tago'),
  ('PH-SUR-TANDAG-CITY', 'PH-SUR', 'Tandag City'),
  ('PH-TAR-ANAO', 'PH-TAR', 'Anao'),
  ('PH-TAR-BAMBAN', 'PH-TAR', 'Bamban'),
  ('PH-TAR-CAMILING', 'PH-TAR', 'Camiling'),
  ('PH-TAR-CAPAS', 'PH-TAR', 'Capas'),
  ('PH-TAR-CONCEPCION', 'PH-TAR', 'Concepcion'),
  ('PH-TAR-GERONA', 'PH-TAR', 'Gerona'),
  ('PH-TAR-LA-PAZ', 'PH-TAR', 'La Paz'),
  ('PH-TAR-MAYANTOC', 'PH-TAR', 'Mayantoc'),
  ('PH-TAR-MONCADA', 'PH-TAR', 'Moncada'),
  ('PH-TAR-PANIQUI', 'PH-TAR', 'Paniqui'),
  ('PH-TAR-PURA', 'PH-TAR', 'Pura'),
  ('PH-TAR-RAMOS', 'PH-TAR', 'Ramos'),
  ('PH-TAR-SAN-CLEMENTE', 'PH-TAR', 'San Clemente'),
  ('PH-TAR-SAN-JOSE', 'PH-TAR', 'San Jose'),
  ('PH-TAR-SAN-MANUEL', 'PH-TAR', 'San Manuel'),
  ('PH-TAR-SANTA-IGNACIA', 'PH-TAR', 'Santa Ignacia'),
  ('PH-TAR-TARLAC-CITY', 'PH-TAR', 'Tarlac City'),
  ('PH-TAR-VICTORIA', 'PH-TAR', 'Victoria'),
  ('PH-TAW-BONGAO', 'PH-TAW', 'Bongao'),
  ('PH-TAW-LANGUYAN', 'PH-TAW', 'Languyan'),
  ('PH-TAW-MAPUN-CAGAYAN-DE-TAWI-TAWI', 'PH-TAW', 'Mapun (Cagayan De Tawi-Tawi)'),
  ('PH-TAW-PANGLIMA-SUGALA-BALIMBING', 'PH-TAW', 'Panglima Sugala (Balimbing)'),
  ('PH-TAW-SAPA-SAPA', 'PH-TAW', 'Sapa-Sapa'),
  ('PH-TAW-SIBUTU', 'PH-TAW', 'Sibutu'),
  ('PH-TAW-SIMUNUL', 'PH-TAW', 'Simunul'),
  ('PH-TAW-SITANGKAI', 'PH-TAW', 'Sitangkai'),
  ('PH-TAW-SOUTH-UBIAN', 'PH-TAW', 'South Ubian'),
  ('PH-TAW-TANDUBAS', 'PH-TAW', 'Tandubas'),
  ('PH-TAW-TURTLE-ISLANDS', 'PH-TAW', 'Turtle Islands'),
  ('PH-WSA-ALMAGRO', 'PH-WSA', 'Almagro'),
  ('PH-WSA-BASEY', 'PH-WSA', 'Basey'),
  ('PH-WSA-CALBAYOG-CITY', 'PH-WSA', 'Calbayog City'),
  ('PH-WSA-CALBIGA', 'PH-WSA', 'Calbiga'),
  ('PH-WSA-CATBALOGAN-CITY', 'PH-WSA', 'Catbalogan City'),
  ('PH-WSA-DARAM', 'PH-WSA', 'Daram'),
  ('PH-WSA-GANDARA', 'PH-WSA', 'Gandara'),
  ('PH-WSA-HINABANGAN', 'PH-WSA', 'Hinabangan'),
  ('PH-WSA-JIABONG', 'PH-WSA', 'Jiabong'),
  ('PH-WSA-MARABUT', 'PH-WSA', 'Marabut'),
  ('PH-WSA-MATUGUINAO', 'PH-WSA', 'Matuguinao'),
  ('PH-WSA-MOTIONG', 'PH-WSA', 'Motiong'),
  ('PH-WSA-PAGSANGHAN', 'PH-WSA', 'Pagsanghan'),
  ('PH-WSA-PARANAS-WRIGHT', 'PH-WSA', 'Paranas (Wright)'),
  ('PH-WSA-PINABACDAO', 'PH-WSA', 'Pinabacdao'),
  ('PH-WSA-SAN-JORGE', 'PH-WSA', 'San Jorge'),
  ('PH-WSA-SAN-JOSE-DE-BUAN', 'PH-WSA', 'San Jose De Buan'),
  ('PH-WSA-SAN-SEBASTIAN', 'PH-WSA', 'San Sebastian'),
  ('PH-WSA-SANTA-MARGARITA', 'PH-WSA', 'Santa Margarita'),
  ('PH-WSA-SANTA-RITA', 'PH-WSA', 'Santa Rita'),
  ('PH-WSA-SANTO-NINO', 'PH-WSA', 'Santo Niño'),
  ('PH-WSA-TAGAPUL-AN', 'PH-WSA', 'Tagapul-An'),
  ('PH-WSA-TALALORA', 'PH-WSA', 'Talalora'),
  ('PH-WSA-TARANGNAN', 'PH-WSA', 'Tarangnan'),
  ('PH-WSA-VILLAREAL', 'PH-WSA', 'Villareal'),
  ('PH-WSA-ZUMARRAGA', 'PH-WSA', 'Zumarraga'),
  ('PH-ZAN-BACUNGAN-LEON-T-POSTIGO', 'PH-ZAN', 'Bacungan (Leon T. Postigo)'),
  ('PH-ZAN-BALIGUIAN', 'PH-ZAN', 'Baliguian'),
  ('PH-ZAN-DAPITAN-CITY', 'PH-ZAN', 'Dapitan City'),
  ('PH-ZAN-DIPOLOG-CITY', 'PH-ZAN', 'Dipolog City'),
  ('PH-ZAN-GODOD', 'PH-ZAN', 'Godod'),
  ('PH-ZAN-GUTALAC', 'PH-ZAN', 'Gutalac'),
  ('PH-ZAN-JOSE-DALMAN-PONOT', 'PH-ZAN', 'Jose Dalman (Ponot)'),
  ('PH-ZAN-KALAWIT', 'PH-ZAN', 'Kalawit'),
  ('PH-ZAN-KATIPUNAN', 'PH-ZAN', 'Katipunan'),
  ('PH-ZAN-LA-LIBERTAD', 'PH-ZAN', 'La Libertad'),
  ('PH-ZAN-LABASON', 'PH-ZAN', 'Labason'),
  ('PH-ZAN-LILOY', 'PH-ZAN', 'Liloy'),
  ('PH-ZAN-MANUKAN', 'PH-ZAN', 'Manukan'),
  ('PH-ZAN-MUTIA', 'PH-ZAN', 'Mutia'),
  ('PH-ZAN-PINAN-NEW-PINAN', 'PH-ZAN', 'Piñan (New Piñan)'),
  ('PH-ZAN-POLANCO', 'PH-ZAN', 'Polanco'),
  ('PH-ZAN-PRES-MANUEL-A-ROXAS', 'PH-ZAN', 'Pres. Manuel A. Roxas'),
  ('PH-ZAN-RIZAL', 'PH-ZAN', 'Rizal'),
  ('PH-ZAN-SALUG', 'PH-ZAN', 'Salug'),
  ('PH-ZAN-SERGIO-OSMENA-SR', 'PH-ZAN', 'Sergio Osmeña Sr.'),
  ('PH-ZAN-SIAYAN', 'PH-ZAN', 'Siayan'),
  ('PH-ZAN-SIBUCO', 'PH-ZAN', 'Sibuco'),
  ('PH-ZAN-SIBUTAD', 'PH-ZAN', 'Sibutad'),
  ('PH-ZAN-SINDANGAN', 'PH-ZAN', 'Sindangan'),
  ('PH-ZAN-SIOCON', 'PH-ZAN', 'Siocon'),
  ('PH-ZAN-SIRAWAI', 'PH-ZAN', 'Sirawai'),
  ('PH-ZAN-TAMPILISAN', 'PH-ZAN', 'Tampilisan'),
  ('PH-ZAS-AURORA', 'PH-ZAS', 'Aurora'),
  ('PH-ZAS-BAYOG', 'PH-ZAS', 'Bayog'),
  ('PH-ZAS-DIMATALING', 'PH-ZAS', 'Dimataling'),
  ('PH-ZAS-DINAS', 'PH-ZAS', 'Dinas'),
  ('PH-ZAS-DUMALINAO', 'PH-ZAS', 'Dumalinao'),
  ('PH-ZAS-DUMINGAG', 'PH-ZAS', 'Dumingag'),
  ('PH-ZAS-GUIPOS', 'PH-ZAS', 'Guipos'),
  ('PH-ZAS-JOSEFINA', 'PH-ZAS', 'Josefina'),
  ('PH-ZAS-KUMALARANG', 'PH-ZAS', 'Kumalarang'),
  ('PH-ZAS-LABANGAN', 'PH-ZAS', 'Labangan'),
  ('PH-ZAS-LAKEWOOD', 'PH-ZAS', 'Lakewood'),
  ('PH-ZAS-LAPUYAN', 'PH-ZAS', 'Lapuyan'),
  ('PH-ZAS-MAHAYAG', 'PH-ZAS', 'Mahayag'),
  ('PH-ZAS-MARGOSATUBIG', 'PH-ZAS', 'Margosatubig'),
  ('PH-ZAS-MIDSALIP', 'PH-ZAS', 'Midsalip'),
  ('PH-ZAS-MOLAVE', 'PH-ZAS', 'Molave'),
  ('PH-ZAS-PAGADIAN-CITY', 'PH-ZAS', 'Pagadian City'),
  ('PH-ZAS-PITOGO', 'PH-ZAS', 'Pitogo'),
  ('PH-ZAS-RAMON-MAGSAYSAY-LIARGO', 'PH-ZAS', 'Ramon Magsaysay (Liargo)'),
  ('PH-ZAS-SAN-MIGUEL', 'PH-ZAS', 'San Miguel'),
  ('PH-ZAS-SAN-PABLO', 'PH-ZAS', 'San Pablo'),
  ('PH-ZAS-SOMINOT-DON-MARIANO-MARCOS', 'PH-ZAS', 'Sominot (Don Mariano Marcos)'),
  ('PH-ZAS-TABINA', 'PH-ZAS', 'Tabina'),
  ('PH-ZAS-TAMBULIG', 'PH-ZAS', 'Tambulig'),
  ('PH-ZAS-TIGBAO', 'PH-ZAS', 'Tigbao'),
  ('PH-ZAS-TUKURAN', 'PH-ZAS', 'Tukuran'),
  ('PH-ZAS-VINCENZO-A-SAGUN', 'PH-ZAS', 'Vincenzo A. Sagun'),
  ('PH-ZAS-ZAMBOANGA-CITY', 'PH-ZAS', 'Zamboanga City'),
  ('PH-ZMB-BOTOLAN', 'PH-ZMB', 'Botolan'),
  ('PH-ZMB-CABANGAN', 'PH-ZMB', 'Cabangan'),
  ('PH-ZMB-CANDELARIA', 'PH-ZMB', 'Candelaria'),
  ('PH-ZMB-CASTILLEJOS', 'PH-ZMB', 'Castillejos'),
  ('PH-ZMB-IBA', 'PH-ZMB', 'Iba'),
  ('PH-ZMB-MASINLOC', 'PH-ZMB', 'Masinloc'),
  ('PH-ZMB-OLONGAPO-CITY', 'PH-ZMB', 'Olongapo City'),
  ('PH-ZMB-PALAUIG', 'PH-ZMB', 'Palauig'),
  ('PH-ZMB-SAN-ANTONIO', 'PH-ZMB', 'San Antonio'),
  ('PH-ZMB-SAN-FELIPE', 'PH-ZMB', 'San Felipe'),
  ('PH-ZMB-SAN-MARCELINO', 'PH-ZMB', 'San Marcelino'),
  ('PH-ZMB-SAN-NARCISO', 'PH-ZMB', 'San Narciso'),
  ('PH-ZMB-SANTA-CRUZ', 'PH-ZMB', 'Santa Cruz'),
  ('PH-ZMB-SUBIC', 'PH-ZMB', 'Subic'),
  ('PH-ZSI-ALICIA', 'PH-ZSI', 'Alicia'),
  ('PH-ZSI-BUUG', 'PH-ZSI', 'Buug'),
  ('PH-ZSI-DIPLAHAN', 'PH-ZSI', 'Diplahan'),
  ('PH-ZSI-IMELDA', 'PH-ZSI', 'Imelda'),
  ('PH-ZSI-IPIL', 'PH-ZSI', 'Ipil'),
  ('PH-ZSI-KABASALAN', 'PH-ZSI', 'Kabasalan'),
  ('PH-ZSI-MABUHAY', 'PH-ZSI', 'Mabuhay'),
  ('PH-ZSI-MALANGAS', 'PH-ZSI', 'Malangas'),
  ('PH-ZSI-NAGA', 'PH-ZSI', 'Naga'),
  ('PH-ZSI-OLUTANGA', 'PH-ZSI', 'Olutanga'),
  ('PH-ZSI-PAYAO', 'PH-ZSI', 'Payao'),
  ('PH-ZSI-ROSELLER-LIM', 'PH-ZSI', 'Roseller Lim'),
  ('PH-ZSI-SIAY', 'PH-ZSI', 'Siay'),
  ('PH-ZSI-TALUSAN', 'PH-ZSI', 'Talusan'),
  ('PH-ZSI-TITAY', 'PH-ZSI', 'Titay'),
  ('PH-ZSI-TUNGAWAN', 'PH-ZSI', 'Tungawan')
ON CONFLICT (code) DO UPDATE
SET
  province_code = EXCLUDED.province_code,
  name = EXCLUDED.name;
