INSERT INTO public.geo_cities_municipalities (code, province_code, name)
VALUES
  ('PH-CEB-ALCANTARA', 'PH-CEB', 'Alcantara'),
  ('PH-CEB-ALCOY', 'PH-CEB', 'Alcoy'),
  ('PH-CEB-ALEGRIA', 'PH-CEB', 'Alegria'),
  ('PH-CEB-ALOGUINSAN', 'PH-CEB', 'Aloguinsan'),
  ('PH-CEB-ARGAO', 'PH-CEB', 'Argao'),
  ('PH-CEB-ASTURIAS', 'PH-CEB', 'Asturias'),
  ('PH-CEB-BADIAN', 'PH-CEB', 'Badian'),
  ('PH-CEB-BALAMBAN', 'PH-CEB', 'Balamban'),
  ('PH-CEB-BANTAYAN', 'PH-CEB', 'Bantayan'),
  ('PH-CEB-BARILI', 'PH-CEB', 'Barili'),
  ('PH-CEB-BOGO-CITY', 'PH-CEB', 'Bogo City'),
  ('PH-CEB-BOLJOON', 'PH-CEB', 'Boljoon'),
  ('PH-CEB-BORBON', 'PH-CEB', 'Borbon'),
  ('PH-CEB-CARCAR-CITY', 'PH-CEB', 'Carcar City'),
  ('PH-CEB-CARMEN', 'PH-CEB', 'Carmen'),
  ('PH-CEB-CATMON', 'PH-CEB', 'Catmon'),
  ('PH-CEB-CEBU-CITY', 'PH-CEB', 'Cebu City'),
  ('PH-CEB-COMPOSTELA', 'PH-CEB', 'Compostela'),
  ('PH-CEB-CONSOLACION', 'PH-CEB', 'Consolacion'),
  ('PH-CEB-CORDOVA', 'PH-CEB', 'Cordova'),
  ('PH-CEB-DAANBANTAYAN', 'PH-CEB', 'Daanbantayan'),
  ('PH-CEB-DALAGUETE', 'PH-CEB', 'Dalaguete'),
  ('PH-CEB-DANAO-CITY', 'PH-CEB', 'Danao City'),
  ('PH-CEB-DUMANJUG', 'PH-CEB', 'Dumanjug'),
  ('PH-CEB-GINATILAN', 'PH-CEB', 'Ginatilan'),
  ('PH-CEB-LAPU-LAPU-CITY-OPON', 'PH-CEB', 'Lapu-Lapu City'),
  ('PH-CEB-LILOAN', 'PH-CEB', 'Liloan'),
  ('PH-CEB-MADRIDEJOS', 'PH-CEB', 'Madridejos'),
  ('PH-CEB-MALABUYOC', 'PH-CEB', 'Malabuyoc'),
  ('PH-CEB-MANDAUE-CITY', 'PH-CEB', 'Mandaue City'),
  ('PH-CEB-MEDELLIN', 'PH-CEB', 'Medellin'),
  ('PH-CEB-MINGLANILLA', 'PH-CEB', 'Minglanilla'),
  ('PH-CEB-MOALBOAL', 'PH-CEB', 'Moalboal'),
  ('PH-CEB-NAGA-CITY', 'PH-CEB', 'Naga City'),
  ('PH-CEB-OSLOB', 'PH-CEB', 'Oslob'),
  ('PH-CEB-PILAR', 'PH-CEB', 'Pilar'),
  ('PH-CEB-PINAMUNGAHAN', 'PH-CEB', 'Pinamungajan'),
  ('PH-CEB-PORO', 'PH-CEB', 'Poro'),
  ('PH-CEB-RONDA', 'PH-CEB', 'Ronda'),
  ('PH-CEB-SAMBOAN', 'PH-CEB', 'Samboan'),
  ('PH-CEB-SAN-FERNANDO', 'PH-CEB', 'San Fernando'),
  ('PH-CEB-SAN-FRANCISCO', 'PH-CEB', 'San Francisco'),
  ('PH-CEB-SAN-REMIGIO', 'PH-CEB', 'San Remigio'),
  ('PH-CEB-SANTA-FE', 'PH-CEB', 'Santa Fe'),
  ('PH-CEB-SANTANDER', 'PH-CEB', 'Santander'),
  ('PH-CEB-SIBONGA', 'PH-CEB', 'Sibonga'),
  ('PH-CEB-SOGOD', 'PH-CEB', 'Sogod'),
  ('PH-CEB-TABOGON', 'PH-CEB', 'Tabogon'),
  ('PH-CEB-TABUELAN', 'PH-CEB', 'Tabuelan'),
  ('PH-CEB-TALISAY-CITY', 'PH-CEB', 'Talisay City'),
  ('PH-CEB-TOLEDO-CITY', 'PH-CEB', 'Toledo City'),
  ('PH-CEB-TUBURAN', 'PH-CEB', 'Tuburan'),
  ('PH-CEB-TUDELA', 'PH-CEB', 'Tudela')
ON CONFLICT (code) DO UPDATE
SET
  province_code = EXCLUDED.province_code,
  name = EXCLUDED.name;
