INSERT INTO public.geo_provinces (code, name)
VALUES
  ('PH-ABR', 'Abra'),
  ('PH-AGN', 'Agusan del Norte'),
  ('PH-AGS', 'Agusan del Sur'),
  ('PH-AKL', 'Aklan'),
  ('PH-ALB', 'Albay'),
  ('PH-ANT', 'Antique'),
  ('PH-APA', 'Apayao'),
  ('PH-AUR', 'Aurora'),
  ('PH-BAS', 'Basilan'),
  ('PH-BAN', 'Bataan'),
  ('PH-BTN', 'Batanes'),
  ('PH-BTG', 'Batangas'),
  ('PH-BEN', 'Benguet'),
  ('PH-BIL', 'Biliran'),
  ('PH-BUK', 'Bukidnon'),
  ('PH-BUL', 'Bulacan'),
  ('PH-CAG', 'Cagayan'),
  ('PH-CAM', 'Camiguin'),
  ('PH-CAN', 'Camarines Norte'),
  ('PH-CAP', 'Capiz'),
  ('PH-CAS', 'Camarines Sur'),
  ('PH-CAT', 'Catanduanes'),
  ('PH-CAV', 'Cavite'),
  ('PH-CEB', 'Cebu'),
  ('PH-COM', 'Davao de Oro'),
  ('PH-DAO', 'Davao Oriental'),
  ('PH-DAS', 'Davao del Sur'),
  ('PH-DAV', 'Davao del Norte'),
  ('PH-DIN', 'Dinagat Islands'),
  ('PH-DVO', 'Davao Occidental'),
  ('PH-EAS', 'Eastern Samar'),
  ('PH-GUI', 'Guimaras'),
  ('PH-IFU', 'Ifugao'),
  ('PH-ILI', 'Iloilo'),
  ('PH-ILN', 'Ilocos Norte'),
  ('PH-ILS', 'Ilocos Sur'),
  ('PH-ISA', 'Isabela'),
  ('PH-KAL', 'Kalinga'),
  ('PH-LAG', 'Laguna'),
  ('PH-LAN', 'Lanao del Norte'),
  ('PH-LAS', 'Lanao del Sur'),
  ('PH-LEY', 'Leyte'),
  ('PH-LUN', 'La Union'),
  ('PH-MAD', 'Marinduque'),
  ('PH-MAS', 'Masbate'),
  ('PH-MDC', 'Occidental Mindoro'),
  ('PH-MDR', 'Oriental Mindoro'),
  ('PH-MGN', 'Maguindanao del Norte'),
  ('PH-MGS', 'Maguindanao del Sur'),
  ('PH-MOU', 'Mountain Province'),
  ('PH-MSC', 'Misamis Occidental'),
  ('PH-MSR', 'Misamis Oriental'),
  ('PH-NCO', 'Cotabato'),
  ('PH-NEC', 'Negros Occidental'),
  ('PH-NER', 'Negros Oriental'),
  ('PH-NSA', 'Northern Samar'),
  ('PH-NUE', 'Nueva Ecija'),
  ('PH-NUV', 'Nueva Vizcaya'),
  ('PH-PAM', 'Pampanga'),
  ('PH-PAN', 'Pangasinan'),
  ('PH-PLW', 'Palawan'),
  ('PH-QUE', 'Quezon'),
  ('PH-QUI', 'Quirino'),
  ('PH-RIZ', 'Rizal'),
  ('PH-ROM', 'Romblon'),
  ('PH-SAR', 'Sarangani'),
  ('PH-SCO', 'South Cotabato'),
  ('PH-SIG', 'Siquijor'),
  ('PH-SLE', 'Southern Leyte'),
  ('PH-SLU', 'Sulu'),
  ('PH-SOR', 'Sorsogon'),
  ('PH-SUK', 'Sultan Kudarat'),
  ('PH-SUN', 'Surigao del Norte'),
  ('PH-SUR', 'Surigao del Sur'),
  ('PH-TAR', 'Tarlac'),
  ('PH-TAW', 'Tawi-Tawi'),
  ('PH-WSA', 'Samar'),
  ('PH-ZAN', 'Zamboanga del Norte'),
  ('PH-ZAS', 'Zamboanga del Sur'),
  ('PH-ZMB', 'Zambales'),
  ('PH-ZSI', 'Zamboanga Sibugay')
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name;

-- Template for province-specific city/municipality seed files,
-- following the existing Bohol seed formatting:
--
-- INSERT INTO public.geo_cities_municipalities (code, province_code, name)
-- VALUES
--   ('PH-CEB-EXAMPLE-CITY', 'PH-CEB', 'Example City')
-- ON CONFLICT (code) DO UPDATE
-- SET
--   province_code = EXCLUDED.province_code,
--   name = EXCLUDED.name;
